### ISSUE TITLE
Replace PHP process isolation code with Symfony Process component

### ISSUE THREAD

**Issue by sun** [sebastianbergmann/phpunit#1342]
Platform-specific process isolation bugs like #1340 are exceptionally hard to debug.

The [Symfony Process component](https://github.com/symfony/process) is a decoupled and very lightweight library.  In essence, a robust wrapper around `proc_open()`.

Proposal:  Replace the `PHPUnit_Util_PHP_*` classes with Symfony `Process`.

Doing this should be relatively straightforward.  However, I don't know whether the backwards compatibility policy also applies to rather internal code of the test runner itself?

**Comment by sebastianbergmann** [comment]
I am no longer convinced that this is the right way to go.

**Comment by allan-simon** [comment]
@sebastianbergmann  Hello  , is it possible to why it's not the right way to go and if you have an other idea on how to tackle the issue of `@runInSeparateProcess` being extremly hard to debug

I spend several days , without success , trying to debug a test failing only in CI environment

the test failed with this error (I put it here in case it help people googling it finding this ticket) 

```
There was 1 error:
1) App\Tests\IntegrationTest\EndUserRegisterTest::testEndUserThatRegistedAndManuallyEnterInvitationCanAccessDashboard
PHPUnit\Framework\Exception: <!-- Serialization of 'Closure' is not allowed (500 Internal Server Error) -->
<!DOCTYPE html>
[lot of Symfony generic error 500 HTML]
*]]>*/        </script>
    </body>
</html>
<!-- Serialization of 'Closure' is not allowed (500 Internal Server Error) -->
Caused by
ErrorException: unserialize(): Error at offset 0 of 53820 bytes in /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:289
Stack trace:
#0 [internal function]: PHPUnit\Util\PHP\AbstractPhpProcess::PHPUnit\Util\PHP\{closure}(8, 'unserialize(): ...', '/builds/rosaly-...', 289)
#1 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(289): unserialize('<!-- Serializat...')
#2 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(187): PHPUnit\Util\PHP\AbstractPhpProcess->processChildResult(Object(App\Tests\IntegrationTest\EndUserRegisterTest), Object(PHPUnit\Framework\TestResult), '<!-- Serializat...', '')
#3 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Util\PHP\AbstractPhpProcess->runTestJob('<?php\nuse PHPUn...', Object(App\Tests\IntegrationTest\EndUserRegisterTest), Object(PHPUnit\Framework\TestResult))
#4 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#5 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(670): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#9 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#10 /builds/rosaly-fintech/backend-php/vendor/phpunit/phpunit/phpunit(92): PHPUnit\TextUI\Command::main()
#11 {main}
```

The symfony error itself (when copy pasting the html into a file) being 

```
Serialization of 'Closure' is not allowed
serialize(array('testResult' => null, 'numAssertions' => 4, 'result' => object(TestResult), 'output' => '')) in /Standard input code (line 89) 
__phpunit_run_isolated_test() in /Standard input code (line 123) 
```

I have no specific way to reproduce it, but it seems to be when an assert fail somewhere or an uncaught exception is thrown , causing the actual exception/assert failure to disapear into oblivion and leaving this opaque error instead 

So right now I am to the point where I think it will be easier for me to do a PR to implement the idea you have on how to tackle this , as I understand `@runInSeparateProcess` tests are not the main use cases for phpunit .
