### ISSUE TITLE
@expectedException not catching destructor exception in HHVM

### ISSUE THREAD

**Issue by vearutop** [sebastianbergmann/phpunit#1640]
PHPUnit catches both exceptions when running with PHP (tested with 5.4 and php-ng) and only first one when running with HHVM. 

```php
class a {
    public function raise() {
        echo "raising\n";
        throw new Exception('Test exception');
    }
    public function __destruct() {
        echo "destructing\n";
        $this->raise();
    }
}

class DoubleExceptionTest extends PHPUnit_Framework_TestCase {
    /**
     * @expectedException     Exception
     */
    public function testDoubleException() {
        $a = new a();
        $a->raise();
    }
}
```
PHP 5.4
```
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /root/yaoi/php-yaoi-tests/phpunit.xml

.raising
destructing
raising


Time: 40 ms, Memory: 4.00Mb

OK (1 test, 1 assertion)
```

HHVM 3.6.0
```
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.

Configuration read from /root/yaoi/php-yaoi-tests/phpunit.xml

Destructor threw an object exception: exception 'Exception' with message 'Test exception' in /root/yaoi/php-yaoi-tests/t1/DoubleExceptionTest.php:5
Stack trace:
#0 /root/yaoi/php-yaoi-tests/t1/DoubleExceptionTest.php(10): a->raise()
#1 /root/yaoi/php-yaoi-tests/t1/DoubleExceptionTest.php(20): a->__destruct()
#2 (): DoubleExceptionTest->testDoubleException()
#3 phar://phpunit-4.5.0.phar/phpunit/Framework/TestCase.php(860): ReflectionMethod->invokeArgs()
#4 phar://phpunit-4.5.0.phar/phpunit/Framework/TestCase.php(737): PHPUnit_Framework_TestCase->runTest()
#5 phar://phpunit-4.5.0.phar/phpunit/Framework/TestResult.php(609): PHPUnit_Framework_TestCase->runBare()
#6 phar://phpunit-4.5.0.phar/phpunit/Framework/TestCase.php(693): PHPUnit_Framework_TestResult->run()
#7 phar://phpunit-4.5.0.phar/phpunit/Framework/TestSuite.php(716): PHPUnit_Framework_TestCase->run()
#8 phar://phpunit-4.5.0.phar/phpunit/Framework/TestSuite.php(716): PHPUnit_Framework_TestSuite->run()
#9 phar://phpunit-4.5.0.phar/phpunit/TextUI/TestRunner.php(398): PHPUnit_Framework_TestSuite->run()
#10 phar://phpunit-4.5.0.phar/phpunit/TextUI/Command.php(152): PHPUnit_TextUI_TestRunner->doRun()
#11 phar://phpunit-4.5.0.phar/phpunit/TextUI/Command.php(104): PHPUnit_TextUI_Command->run()
#12 /root/yaoi/php-yaoi-tests/phpunit.phar(722): PHPUnit_TextUI_Command::main()
#13 {main}
.raising
destructing
raising


Time: 1.13 seconds, Memory: 17.32Mb

OK (1 test, 1 assertion)
```

**Comment by arvenil** [comment]
Possible reason https://github.com/facebook/hhvm/blob/af329776c9f740cc1c8c4791f673ba5aa49042ce/hphp/doc/inconsistencies#L40-L48

**Comment by fredemmott** [comment]
This is not a PHPUnit bug - HHVM isn't throwing the exception: https://3v4l.org/3sXAl . Can you file an issue against HHVM to either remove that inconsistency (linked by @arvenil), or add an explanation for why it exists?
