### ISSUE TITLE
EngineExceptions (eg TypeException) can not be detected using @expectedException (PHP 7)

### ISSUE THREAD

**Issue by throup** [sebastianbergmann/phpunit#1748]
PHP 7 introduces `EngineException`s in place of fatal errors.  These exceptions are not detected when annotated with `@expectedException`. In fact, the test runner will fail unless these exceptions are manually caught.

As a simple example, consider the class:
``` php
<?php
declare(strict_types = 1);

class ScalarType {
    public function expectsInteger(int $integer) {
        // Do nothing
    }
}
```

and the testcase:
``` php
<?php
declare(strict_types = 1);

class ScalarTypeTest extends PHPUnit_Framework_TestCase {
    /**
     * @test
     * @expectedException TypeException
     */
    public function passStringWhenIntegerExpected() {
        $sut = new ScalarType();
        $sut->expectsInteger('Not an integer');
    }
}
```

The test runner output:
``` bash
$ phpunit tests/ScalarTypeTest.php 
PHPUnit 4.7.3 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught TypeException: Argument 1 passed to ScalarType::expectsInteger() must be of the type integer, string given, called in .../PHPUnitTests/tests/ScalarTypeTest.php on line 11 and defined in .../PHPUnitTests/src/ScalarType.php:5
Stack trace:
#0 .../PHPUnitTests/tests/ScalarTypeTest.php(11): ScalarType->expectsInteger('Not an integer')
#1 [internal function]: ScalarTypeTest->passStringWhenIntegerExpected()
#2 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestCase.php(863): ReflectionMethod->invokeArgs(Object(ScalarTypeTest), Array)
#3 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestCase.php(741): PHPUnit_Framework_TestCase->runTest()
#4 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestResult.php(605): PHPUnit_Framework_TestCase->runBare()
#5 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestCa in .../PHPUnitTests/src/ScalarType.php on line 5

Fatal error: Uncaught TypeException: Argument 1 passed to ScalarType::expectsInteger() must be of the type integer, string given, called in .../PHPUnitTests/tests/ScalarTypeTest.php on line 11 and defined in .../PHPUnitTests/src/ScalarType.php:5
Stack trace:
#0 .../PHPUnitTests/tests/ScalarTypeTest.php(11): ScalarType->expectsInteger('Not an integer')
#1 [internal function]: ScalarTypeTest->passStringWhenIntegerExpected()
#2 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestCase.php(863): ReflectionMethod->invokeArgs(Object(ScalarTypeTest), Array)
#3 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestCase.php(741): PHPUnit_Framework_TestCase->runTest()
#4 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestResult.php(605): PHPUnit_Framework_TestCase->runBare()
#5 .../PHPUnitTests/vendor/phpunit/phpunit/src/Framework/TestCa in .../PHPUnitTests/src/ScalarType.php on line 5
```

This was with the latest release of PHPUnit 4.7.3 installed using composer. The same result occurs if using the current dev-master.

As far as I can tell, this is because `EngineException` does not derive from the `Exception` class; instead, they both derive from the new `BaseException` class.

This was tested with the latest alpha release of PHP 7 [PHP 7.0.0alpha1 (cli) (built: Jun  9 2015 17:55:52)] installed on Fedora 22 from the remi repository.

**Comment by sebastianbergmann** [comment]
I am aware of the issue but will not address it before the [Throwable](https://wiki.php.net/rfc/throwable-interface) has been implemented.

**Comment by throup** [comment]
Sounds like a fair approach, @sebastianbergmann.
