### ISSUE TITLE
phpdbg coverage reporting gives fatal errors as of php 7.0.7

### ISSUE THREAD

**Issue by jonnybarnes** [sebastianbergmann/phpunit#2179]
It happens even in a brand new laravel app:

```shell
╭─jonny@jonny-arch in /tmp 
╰$ laravel new coverae-test
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  (removed for brevity)
Generating autoload files
> php -r "copy('.env.example', '.env');"
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
Generating optimized class loader
> php artisan key:generate
Application key [base64:nfuPliSo08wQtYWX2+xCwX04l5vC3lL8bhOjtc14XAA=] set successfully.
Application ready! Build something amazing.
╭─jonny@jonny-arch in /tmp 
╰$ cd coverae-test 
╭─jonny@jonny-arch in /tmp/coverae-test 
╰$ phpdbg -qrr vendor/bin/phpunit --coverage-text
PHPUnit 4.8.26 by Sebastian Bergmann and contributors.

.

Time: 128 ms, Memory: 16.00MB

OK (1 test, 2 assertions)
[PHP Fatal error:  Cannot declare class App\Http\Controllers\Controller, because the name is already in use in /tmp/coverae-test/app/Http/Controllers/Controller.php on line 11]
[PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#2 /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#3 /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#4 /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): in /tmp/coverae-test/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752
```

**Comment by sebastianbergmann** [comment]
This [should](https://github.com/sebastianbergmann/phpunit/blob/master/CONTRIBUTING.md#reporting-issues) have been reported on the [php-code-coverage](https://github.com/sebastianbergmann/php-code-coverage) project.

As a sidenote, PHPUnit 4.8 is not supported on PHP 7.
