### ISSUE TITLE
Weird error when trying to run `Test` from `Test.php` but `Test.php` does not exist

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#2448]
## Expected
```
$ phpunit Test
Cannot open file "Test.php".
```
## Actual
```
$ phpunit Test
PHP Fatal error:  Uncaught PHPUnit\Runner\Exception: Class 'PHPUnit\Util\Test' could not be found in 'Test.php'. in /usr/local/src/phpunit/src/Runner/StandardTestSuiteLoader.php:107
Stack trace:
#0 /usr/local/src/phpunit/src/Runner/BaseTestRunner.php(130): PHPUnit\Runner\StandardTestSuiteLoader->load('PHPUnit\\Util\\Te...', 'Test.php')
#1 /usr/local/src/phpunit/src/Runner/BaseTestRunner.php(71): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('Test', '')
#2 /usr/local/src/phpunit/src/TextUI/Command.php(159): PHPUnit\Runner\BaseTestRunner->getTest('Test', '', Array)
#3 /usr/local/src/phpunit/src/TextUI/Command.php(136): PHPUnit\TextUI\Command->run(Array, true)
#4 /usr/local/src/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#5 {main}
  thrown in /usr/local/src/phpunit/src/Runner/StandardTestSuiteLoader.php on line 107

```

**Comment by webmailcontatos** [comment]
I did find the problem but i don't know create a test for simulate the issue. I need create a test for send a pr. Tip for solution the issue :

Class : Class PHPUnit_Util_Fileloader
Method :  public static function checkAndLoad($filename)
The problem reason  : There are one class called Test.php
My solution : 
```
public static function checkAndLoad($filename)
    {
        $includePathFilename = stream_resolve_include_path($filename);
        $isFile = is_file(__DIR__ . DIRECTORY_SEPARATOR . $filename);

        if (!$includePathFilename || !is_readable($includePathFilename) || $isFile) {
            throw new PHPUnit_Framework_Exception(
                sprintf('Cannot open file "%s".' . "\n", $filename)
            );
        }

        self::load($includePathFilename);

        return $includePathFilename;
    }
```

**Comment by sebastianbergmann** [comment]
Actually, the **Expected** section shown above is wrong, too, as it is missing the PHPUnit "header". It should be
```
$ phpunit FooTest
PHPUnit 6.0.11-15-g7d9130c by Sebastian Bergmann and contributors.

Cannot open file "FooTest.php".
```
