### ISSUE TITLE
Failed to open `//usr/sbin/authserver` ?

### ISSUE THREAD

**Issue by apfelbox** [sebastianbergmann/phpunit#2845]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.4.3 / 5.7.23
| PHP version         | 7.1.11
| Installation Method | PHAR
| OS | macOS 10.13.1

Hi,

I have a testsuite that I can run without any problems:

```bash
php phpunit-5.7.23.phar -c phpunit.xml --log-junit shippable/testresults/junit.xml --verbose
php phpunit-6.4.3.phar -c phpunit.xml --log-junit shippable/testresults/junit.xml --verbose
```

Both of them work without any issues.

But as soon as I add code coverage ...
```bash
php phpunit-5.7.23.phar -c phpunit.xml --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage --verbose
php phpunit-6.4.3.phar -c phpunit.xml --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage --verbose
```
 I get:

```
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.11 with Xdebug 2.5.5
Configuration: /my-project-path/phpunit.xml

PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(//usr/sbin/authserver): failed to open dir: Permission denied in phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php:64
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct('//usr/sbin/auth...', 512)
#1 [internal function]: RecursiveDirectoryIterator->getChildren()
#2 [internal function]: FilterIterator->rewind()
#3 phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php(64): AppendIterator->append(Object(File_Iterator))
#4 phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Facade.php(37): File_Iterator_Factory->getFileIterator(Array, Array, Array, Array)
#5 phar:///my-project-path/phpunit-5.7.23.phar/php-code-coverage/Filter.php(35): File_Iterator_Facade->getFilesAsArray(Array, '.php', '')
#6 phar:///my-project-path/phpunit-5.7.23.phar/phpunit/TextUI/Te in phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php on line 64

Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(//usr/sbin/authserver): failed to open dir: Permission denied in phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php on line 64

UnexpectedValueException: RecursiveDirectoryIterator::__construct(//usr/sbin/authserver): failed to open dir: Permission denied in phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php on line 64

Call Stack:
    0.0090     835824   1. {main}() /my-project-path/phpunit-5.7.23.phar:0
    0.0676    9222400   2. PHPUnit_TextUI_Command::main(???) /my-project-path/phpunit-5.7.23.phar:592
    0.0677    9222512   3. PHPUnit_TextUI_Command->run(array(8), true) phar:///my-project-path/phpunit-5.7.23.phar/phpunit/TextUI/Command.php:116
    0.0823    9486464   4. PHPUnit_TextUI_TestRunner->doRun(class PHPUnit_Framework_TestSuite, array(55), true) phar:///my-project-path/phpunit-5.7.23.phar/phpunit/TextUI/Command.php:186
    0.0863    9493504   5. SebastianBergmann\CodeCoverage\Filter->addDirectoryToWhitelist(string(1), string(4), string(0)) phar:///my-project-path/phpunit-5.7.23.phar/phpunit/TextUI/TestRunner.php:439
    0.0863    9493544   6. File_Iterator_Facade->getFilesAsArray(array(1), string(4), string(0), ???, ???) phar:///my-project-path/phpunit-5.7.23.phar/php-code-coverage/Filter.php:35
    0.0863    9493960   7. File_Iterator_Factory->getFileIterator(array(1), array(1), array(0), array(0)) phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Facade.php:37
    0.0864    9497608   8. AppendIterator->append(class File_Iterator) phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php:64
    0.0864    9498040   9. File_Iterator->rewind() phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php:64
    0.3369    9503544  10. RecursiveDirectoryIterator->getChildren() phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php:64
    0.3369    9504872  11. RecursiveDirectoryIterator->__construct(string(21), long) phar:///my-project-path/phpunit-5.7.23.phar/php-file-iterator/Factory.php:64
```

I have no idea where to which of the packages this error message belongs, so I am asking in the repository which I am directly using. I also tried to search for `authserver` but didn't find anything here.

**Comment by sebastianbergmann** [comment]
Neither the code of PHPUnit nor the code of any of its dependencies contains the string `authserver`.

**Comment by apfelbox** [comment]
Okay, I still get this error when using PhpUnit, so maybe some investigation might help other people who have the same error:

First clue is that there indeed is a `/usr/sbin/authserver` file, which seems to belong to a [Mac OSX Password Server](https://www.unix.com/man-page/osx/8/weakpass_edit/) that has quite strict permissins (`drwx------    - root  16 Jul  0:36 authserver`).

A simple `find /usr -name php` directly triggers this error (as described here https://stackoverflow.com/questions/29250771/how-to-get-php-to-run-from-terminal/29257416), which could be connected with the issue in PhpUnit, as it is triggered in a DirectoryIterator.

In my `phpunit.xml` I have

```xml
<filter>
    <whitelist>
        <directory suffix=".php">/</directory>
    </whitelist>
    <exclude>
        <directory>/tests/</directory>
        <directory>/vendor/</directory>
    </exclude>
</filter>
```

but these paths seem to not be absolute to the `phpunit.xml` (similar to an `chroot` which I would have guessed), but seem to be really absolute on the complete machine.

A simple change to

```xml
<filter>
    <whitelist>
        <directory suffix=".php">./</directory>
    </whitelist>
    <exclude>
        <directory>./tests/</directory>
        <directory>./vendor/</directory>
    </exclude>
</filter>
```

seems to have fixed this issue.
I couldn't find anything in the docs about how the paths are composed and where they start from.

Thanks for your help, this issue is resolved.
