### ISSUE TITLE
TypeError and undefined index when running --version with PHP 7.2 

### ISSUE THREAD

**Issue by lferro9000** [sebastianbergmann/phpunit#2894]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 6.5.2
| PHP version         | 7.2.0
| Installation Method | Composer

In a clean folder i did composer init, followed with composer require --dev phpunit/phpunit.

When running:

```bash
vendor/bin/phpunit --version
```

I got the following output:

```bash
$ vendor/bin/phpunit
PHPUnit 6.5.2 by Sebastian Bergmann and contributors.

Usage: phpunit [options] UnitTest [UnitTest.php]
       phpunit [options] <directory>

Code Coverage Options:

  --coverage-clover <file>    Generate code coverage report in Clover XML format.
  --coverage-crap4j <file>    Generate code coverage report in Crap4J XML format.
  --coverage-html <dir>       Generate code coverage report in HTML format.
  --coverage-php <file>       Export PHP_CodeCoverage object to file.
  --coverage-text=<file>      Generate code coverage report in text format.
                              Default: Standard output.
  --coverage-xml <dir>        Generate code coverage report in PHPUnit XML format.
  --whitelist <dir>           Whitelist <dir> for code coverage analysis.
  --disable-coverage-ignore   Disable annotations for ignoring code coverage.

Logging Options:

  --log-junit <file>          Log test execution in JUnit XML format to file.
  --log-teamcity <file>       Log test execution in TeamCity format to file.
  --testdox-html <file>       Write agile documentation in HTML format to file.
  --testdox-text <file>       Write agile documentation in Text format to file.
  --testdox-xml <file>        Write agile documentation in XML format to file.
  --reverse-list              Print defects in reverse order

Test Selection Options:

  --filter <pattern>          Filter which tests to run.
  --testsuite <name,...>      Filter which testsuite to run.
  --group ...                 Only runs tests from the specified group(s).
  --exclude-group ...         Exclude tests from the specified group(s).
  --list-groups               List available test groups.
  --list-suites               List available test suites.
  --list-tests                List available tests.
  --list-tests-xml <file>     List available tests in XML format.
  --test-suffix ...           Only search for test in files with specified
                              suffix(es). Default: Test.php,.phpt

Test Execution Options:

  --dont-report-useless-tests Do not report tests that do not test anything.
  --strict-coverage           Be strict about @covers annotation usage.
  --strict-global-state       Be strict about changes to global state
  --disallow-test-output      Be strict about output during tests.
  --disallow-resource-usage   Be strict about resource usage during small tests.
  --enforce-time-limit        Enforce time limit based on test size.
  --disallow-todo-tests       Disallow @todo-annotated tests.

  --process-isolation         Run each test in a separate PHP process.
  --globals-backup            Backup and restore $GLOBALS for each test.
  --static-backup             Backup and restore static attributes for each test.

  --colors=<flag>             Use colors in output ("never", "auto" or "always").
  --columns <n>               Number of columns to use for progress output.
  --columns max               Use maximum number of columns for progress output.
  --stderr                    Write to STDERR instead of STDOUT.
  --stop-on-error             Stop execution upon first error.
  --stop-on-failure           Stop execution upon first error or failure.
  --stop-on-warning           Stop execution upon first warning.
  --stop-on-risky             Stop execution upon first risky test.
  --stop-on-skipped           Stop execution upon first skipped test.
  --stop-on-incomplete        Stop execution upon first incomplete test.
  --fail-on-warning           Treat tests with warnings as failures.
  --fail-on-risky             Treat risky tests as failures.
  -v|--verbose                Output more verbose information.
  --debug                     Display debugging information.

  --loader <loader>           TestSuiteLoader implementation to use.
  --repeat <times>            Runs the test(s) repeatedly.
  --teamcity                  Report test execution progress in TeamCity format.
  --testdox                   Report test execution progress in TestDox format.
  --testdox-group             Only include tests from the specified group(s).
  --testdox-exclude-group     Exclude tests from the specified group(s).
  --printer <printer>         TestListener implementation to use.

Configuration Options:

  --bootstrap <file>          A "bootstrap" PHP file that is run before the tests.
  -c|--configuration <file>   Read configuration from XML file.
  --no-configuration          Ignore default configuration file (phpunit.xml).
  --no-coverage               Ignore code coverage configuration.
  --no-logging                Ignore logging configuration.
  --no-extensions             Do not load PHPUnit extensions.
  --include-path <path(s)>    Prepend PHP's include_path with given path(s).
  -d key[=value]              Sets a php.ini value.
  --generate-configuration    Generate configuration file with suggested settings.

Miscellaneous Options:

  -h|--help                   Prints this usage information.
  --version                   Prints the version and exits.
  --atleast-version <min>     Checks that version is greater than min and exits.
  --check-version             Check whether PHPUnit is the latest version.
PHP Notice:  Undefined index: test in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php on line 163

Notice: Undefined index: test in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php on line 163
PHP Notice:  Undefined index: test in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php on line 167

Notice: Undefined index: test in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php on line 167
Cannot open file ".php".

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPUnit\TextUI\TestRunner::doRun() must be an instance of PHPUnit\Framework\Test, null given, called in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php on line 195 and defined in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:185
Stack trace:
#0 /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(NULL, Array, true)
#1 /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#2 /Users/user/dev/test/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#3 {main}
  thrown in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 185

Fatal error: Uncaught TypeError: Argument 1 passed to PHPUnit\TextUI\TestRunner::doRun() must be an instance of PHPUnit\Framework\Test, null given, called in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php on line 195 and defined in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:185
Stack trace:
#0 /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(NULL, Array, true)
#1 /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#2 /Users/user/dev/test/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#3 {main}
  thrown in /Users/user/dev/test/vendor/phpunit/phpunit/src/TextUI/TestRunner.php on line 185
```

This happens on a MacOS machine with High Sierra (10.13.1), with the disk in APFS (Case-sensitive, Encrypted).

The encrypted is not relevant, but the Case sensitiveness may be.

Identical errors happen when installing either as global in composer or with homebrew (as it installs the same version).

**Comment by kubawerlos** [comment]
By any chance have you created or copied `phpunit.xml` or any test to the folder?

**Comment by lferro9000** [comment]
This is with an empty project. No phpunit.xml file, just typing:

```bash
phpunit --version
```

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
```
$ mkdir phpunit-2894
```
```
$ cd phpunit-2894 
```
```
$ composer require --dev phpunit/phpunit
Using version ^6.5 for phpunit/phpunit
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 28 installs, 0 updates, 0 removals
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.4): Downloading (100%)         
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.4): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (4.2.0): Loading from cache
  - Installing phpspec/prophecy (1.7.3): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.2): Downloading (100%)         
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
Writing lock file
Generating autoload files
```
```
$ vendor/bin/phpunit --version
PHPUnit 6.5.2 by Sebastian Bergmann and contributors.
```

**Comment by lferro9000** [comment]
I can't replicate it either on my High Sierra computer with case insensitive file system.

So I suspect it has something to do with it (which i'm not sure if it is something to be worried about at all as it is not a common setup - I only did it as an experiment in any case).

**Comment by karpovigorok** [comment]
for php 7.2 you should use phpunit 7
follow the link https://phpunit.de/getting-started-with-phpunit.html
