### ISSUE TITLE
Directories are not created recursively

### ISSUE THREAD

**Issue by kleisauke** [sebastianbergmann/phpunit#3000]
| Q                   | A
| --------------------| ---------------
| PHPUnit version   | 7.0.0
| PHP version          | 7.1.11 & PHP 7.2.1
| Xdebug version    | 2.5.5
| Installation Method | Composer
| CI environment | Travis CI

[This patch](https://github.com/sebastianbergmann/php-code-coverage/commit/583c4e79cb597763b846010da6e423c4cdb2f39e#diff-19b24179073358fac0d4c1ab22d06243R237) should also be applied to https://github.com/sebastianbergmann/phpunit/blob/ef2c7372cabee8d0eee0d60fd2e2cfb2e4b82ea3/src/Util/Printer.php#L56

Relevant issue: https://github.com/sebastianbergmann/php-code-coverage/issues/584.

Travis log:
https://travis-ci.org/andrieslouw/imagesweserv/builds/339592842

```
PHPUnit 7.0.0 by Sebastian Bergmann and contributors.
PHP Fatal error:  Uncaught RuntimeException: Directory "/home/travis/build/andrieslouw/imagesweserv/build/logs" was not created in /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/Util/Printer.php:57
Stack trace:
#0 /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/Util/Log/JUnit.php(117): PHPUnit\Util\Printer->__construct('/home/travis/bu...')
#1 /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(347): PHPUnit\Util\Log\JUnit->__construct('/home/travis/bu...', true)
#2 /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/TextUI/Command.php(205): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#3 /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/TextUI/Command.php(153): PHPUnit\TextUI\Command->run(Array, true)
#4 /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#5 {main}
  thrown in /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/Util/Printer.php on line 57
Fatal error: Uncaught RuntimeException: Directory "/home/travis/build/andrieslouw/imagesweserv/build/logs" was not created in /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/Util/Printer.php on line 57
RuntimeException: Directory "/home/travis/build/andrieslouw/imagesweserv/build/logs" was not created in /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/Util/Printer.php on line 57
Call Stack:
    0.0001     370488   1. {main}() /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/phpunit:0
    0.0105    1723336   2. PHPUnit\TextUI\Command::main() /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/phpunit:53
    0.0105    1732128   3. PHPUnit\TextUI\Command->run() /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/TextUI/Command.php:153
    0.2234    7336376   4. PHPUnit\TextUI\TestRunner->doRun() /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/TextUI/Command.php:205
    0.2257    7575152   5. PHPUnit\Util\Log\JUnit->__construct() /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:347
    0.2257    7575392   6. PHPUnit\Util\Log\JUnit->__construct() /home/travis/build/andrieslouw/imagesweserv/vendor/phpunit/phpunit/src/Util/Log/JUnit.php:117
```

**Comment by shadowhand** [comment]
This fix fails when using `composer update --prefer-lowest`, see this build which is using `phpunit/phpunit 7.0.2` and `phpunit/php-code-coverage 6.0.0`:

https://travis-ci.org/northwoods/container/jobs/358445969#L568-L586

I propose that a new release `7.0.3` be created that uses `"phpunit/php-code-coverage": "^6.0.2"`.

**Comment by sebastianbergmann** [comment]
https://github.com/sebastianbergmann/phpunit/blob/7.0.3/composer.json#L34
