### ISSUE TITLE
PHPUNIT visit() returns alway 404 error

### ISSUE THREAD

**Issue by ArthurFelix559** [sebastianbergmann/phpunit#3256]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 4.8.36
| PHP version         |  7.2.5
| Installation Method | Composer / PHAR

I'm trying to make some phpunit tests in my API, i have my home route `http://site.intradecloud.test/`, i can access this page in the browser, and when i make an `$this->route('GET', '/')` on my test, it's works, but when i make an `$this->visit('/')` it returns =
```
There was 1 failure:

1) MainPageTest::testExample
A request to [http://site.intradecloud.test/pt-BR] failed. Received status code [404].

/home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php:165
/home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php:63
/home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Foundation/Testing/InteractsWithPages.php:44
/home/vagrant/sites/site/tests/MainPageTest.php:11

Caused by
Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:161
Stack trace:
#0 /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(750): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request)) #1 /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /home/vagrant/sites/site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
```

And a lot of other code
How can i visit my page to make the tests like SEE anything or CLICK in a button. Thanks

I'm using laravel 5.1

**Comment by sebastianbergmann** [comment]
PHPUnit does not have a `visit()` method.

**Comment by sebastianbergmann** [comment]
Please ask this question in a Laravel forum.
