### ISSUE TITLE
[7.4.1] regression 

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/phpunit#3354]
From fedora QA, 7.4.1 break some test suite
e.g. php-cs-fixer one
https://apps.fedoraproject.org/koschei/package/php-cs-fixer?collection=f30

```
PHP Warning:  str_repeat(): Second argument has to be greater than or equal to 0 in /usr/share/php/PHPUnit7/TextUI/ResultPrinter.php on line 501
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PHPUnit\Util\Printer::write() must be of the type string, null given, called in /usr/share/php/PHPUnit7/TextUI/ResultPrinter.php on line 501 and defined in /usr/share/php/PHPUnit7/Util/Printer.php:96
Stack trace:
#0 /usr/share/php/PHPUnit7/TextUI/ResultPrinter.php(501): PHPUnit\Util\Printer->write(NULL)
#1 /usr/share/php/PHPUnit7/TextUI/ResultPrinter.php(300): PHPUnit\TextUI\ResultPrinter->writeProgress('.')
#2 /usr/share/php/PHPUnit7/Framework/TestResult.php(412): PHPUnit\TextUI\ResultPrinter->endTest(Object(PhpCsFixer\Tests\WordMatcherTest), 2.9087066650391E-5)
#3 /usr/share/php/PHPUnit7/Framework/TestResult.php(893): PHPUnit\Framework\TestResult->endTest(Object(PhpCsFixer\Tests\WordMatcherTest), 2.9087066650391E-5)
#4 /usr/share/php/PHPUnit7/Framework/TestCase.php(798): PHPUnit\Framework\TestResult->run(Object(PhpCsFixer\Tests\WordMatcherTest))
#5 /usr/share/php/PHPUnit7/Framework/TestSuite.php(750): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResul in /usr/share/php/PHPUnit7/Util/Printer.php on line 96
```

**Comment by remicollet** [comment]
Notice: output have `Less than 16 columns requested, number of columns set to 16` while configuration file have `colums="max"`
