### ISSUE TITLE
Blacklist initialize class_exists should not call autoloader?

### ISSUE THREAD

**Issue by jonaz** [sebastianbergmann/phpunit#3451]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.1
| PHP version         | 7.3.0
| Installation Method | Composer

I want to be able to see our real errors without having to install dbunit which is abandoned. 

Perhaps the real issue is that phpunit tries to blacklist things its not responsible for (DbUnit). But adding false to the class_exists call would solve the problem i guess. 

https://github.com/sebastianbergmann/phpunit/blob/master/src/Util/Blacklist.php#L105

```
1) Mapper\InvoiceListMapperTest::testThatYearTransferIsUsingOldQuery
PHP Warning:  Uncaught ErrorException: require(PHPUnit/DbUnit/TestCase.php): failed to open stream: No such file or directory in /home/jonaz/git/webapp/application/shared/Support/AutoLoader.php:47
Stack trace:
#0 /home/jonaz/git/webapp/application/shared/Support/AutoLoader.php(47): shared\Support\ErrorHandler::handleError(2, 'require(PHPUnit...', '/home/jonaz/git...', 47, Array)
#1 /home/jonaz/git/webapp/application/shared/Support/AutoLoader.php(47): require()
#2 [internal function]: shared\Support\AutoLoader::loadClass('PHPUnit\\DbUnit\\...')
#3 [internal function]: spl_autoload_call('PHPUnit\\DbUnit\\...')
#4 /home/jonaz/git/webapp/vendor/phpunit/phpunit/src/Util/Blacklist.php(105): class_exists('PHPUnit\\DbUnit\\...')
#5 /home/jonaz/git/webapp/vendor/phpunit/phpunit/src/Util/Blacklist.php(88): PHPUnit\Util\Blacklist->initialize()
#6 /home/jonaz/git/webapp/vendor/phpunit/phpunit/src/Util/Filter.php(58): PHPUnit\Util\Blacklist->isBlackliste in /home/jonaz/git/webapp/application/shared/Support/AutoLoader.php on line 47

```

**Comment by jonaz** [comment]
This solution works. Now i see which tests that failed and not fatal error on require.
You want PR?

```
diff --git a/src/Util/Blacklist.php b/src/Util/Blacklist.php
index 9af4bb511..b78eb74fd 100644
--- a/src/Util/Blacklist.php
+++ b/src/Util/Blacklist.php
@@ -102,7 +102,7 @@ private function initialize(): void
             self::$directories = [];
 
             foreach (self::$blacklistedClassNames as $className => $parent) {
-                if (!\class_exists($className)) {
+                if (!\class_exists($className,false)) {
                     continue;
                 }

```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by jonaz** [comment]
reproducing-example:
```
git clone https://github.com/jonaz/phpunit-bug.git
cd phpunit-bug
./reproduce.sh
```

Output:
```
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 153 ms, Memory: 4.00MB

There was 1 error:

1) EmailTest::testError
PHP Warning:  require(PHPUnit/DbUnit/TestCase.php): failed to open stream: No such file or directory in /tmp/phpunit-bug/autoload.php on line 24

Warning: require(PHPUnit/DbUnit/TestCase.php): failed to open stream: No such file or directory in /tmp/phpunit-bug/autoload.php on line 24
PHP Fatal error:  require(): Failed opening required 'PHPUnit/DbUnit/TestCase.php' (include_path='.:') in /tmp/phpunit-bug/autoload.php on line 24

Fatal error: require(): Failed opening required 'PHPUnit/DbUnit/TestCase.php' (include_path='.:') in /tmp/phpunit-bug/autoload.php on line 24
```

Expected output was to see the real error from the test case: 
```
PHPUnit 7.5.1 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 2.83 seconds, Memory: 4.00MB

There was 1 error:

1) EmailTest::testError
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

/tmp/phpunit-bug/src/Email.php:8
/tmp/phpunit-bug/tests/EmailTest.php:10

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.

```


This fixes the problem:
```
diff --git a/src/Util/Blacklist.php b/src/Util/Blacklist.php
index 9af4bb511..b78eb74fd 100644
--- a/src/Util/Blacklist.php
+++ b/src/Util/Blacklist.php
@@ -102,7 +102,7 @@ private function initialize(): void
             self::$directories = [];
 
             foreach (self::$blacklistedClassNames as $className => $parent) {
-                if (!\class_exists($className)) {
+                if (!\class_exists($className,false)) {
                     continue;
                 }
```

**Comment by gmegidish** [comment]
I'm experiencing the same problem with our source tree. @jonaz's patch fixed the problem. Otherwise it tries to load classes that are not a part of our composer.

**Comment by sebastianbergmann** [comment]
If you run into issues like this then I have to assume that your autoloader is broken.

**Comment by gmegidish** [comment]
@sebastianbergmann Yeah, just got back to this thread to reply that we've found that our autoloader require_onces and was never prepared for this. Fixed that. Got back to comment that it's our fault :) Thanks Sebastian! 👍
