### ISSUE TITLE
No code coverage driver available when using @runInSeparateProcess

### ISSUE THREAD

**Issue by panosru** [sebastianbergmann/phpunit#3492]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 7.5.2
| PHP version         | 7.2.8
| Installation Method | Composer 

Hello, when I use `@runInSeparateProcess` in a test I’m getting a fatal error `Fatal error: Uncaught SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available` but xdebug is properly installed.

```
PHPUnit\Framework\Exception: Fatal error: Uncaught SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available in /***/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:897
Stack trace:
#0 /***/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(146): SebastianBergmann\CodeCoverage\CodeCoverage->selectDriver(Object(SebastianBergmann\CodeCoverage\Filter))
#1 Standard input code(409): SebastianBergmann\CodeCoverage\CodeCoverage->__construct(NULL, Object(SebastianBergmann\CodeCoverage\Filter))
#2 Standard input code(841): __phpunit_run_isolated_test()
#3 {main}
  thrown in /***/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 897
```

This is how my `phpunit.xml.dist` file looks like:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/7.2/phpunit.xsd"
        backupGlobals="false"
        backupStaticAttributes="false"
        bootstrap="vendor/autoload.php"
        cacheTokens="true"
        colors="true"
        convertErrorsToExceptions="true"
        convertNoticesToExceptions="true"
        convertWarningsToExceptions="true"
        forceCoversAnnotation="true"
        printerClass="PHPUnit\TextUI\ResultPrinter"
        processIsolation="false"
        stopOnError="false"
        stopOnFailure="false"
        stopOnIncomplete="false"
        stopOnSkipped="false"
        stopOnRisky="false"
        testSuiteLoaderClass="PHPUnit\Runner\StandardTestSuiteLoader"
        timeoutForSmallTests="1"
        timeoutForMediumTests="10"
        timeoutForLargeTests="60"
        verbose="true">

    <testsuites>
        <testsuite name="Omega FaultManager Unit Test Suite">
            <directory suffix="Test.php">tests/unit</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
            <exclude>
                <directory>vendor</directory>
                <directory suffix=".php">tests</directory>
                <directory suffix=".php">_compiled</directory>
            </exclude>
        </whitelist>
    </filter>

    <logging>
        <log type="coverage-html"
             target="tests/coverage/html"
             showUncoveredFiles="true"
             lowUpperBound="60"
             highLowerBound="95" />
        <log type="coverage-clover"
             target="tests/coverage/clover.xml"
             showUncoveredFiles="true" />
        <log type="coverage-php"
             target="tests/coverage/coverage.serialized"
             showUncoveredFiles="true" />
        <log type="coverage-text"
             target="php://stdout"
             showUncoveredFiles="true" />
        <log type="testdox-html" target="tests/coverage/testdox.html" />
        <log type="testdox-text" target="php://stdout" />
    </logging>

</phpunit>
```

When I run `phpunit --no-coverage` it works fine obviously.

```
$ php -v
PHP 7.2.8 (cli) (built: Aug 28 2018 16:32:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0alpha1, Copyright (c) 2002-2018, by Derick Rethans
    with blackfire v1.24.2~mac-x64-non_zts72, https://blackfire.io, by Blackfire

$ phpunit --version
PHPUnit 7.5.2 by Sebastian Bergmann and contributors.

$ composer info | sort
doctrine/instantiator              1.1.0      A small, lightweight utility to instantiate objects in PHP without invoking their constructors
hamcrest/hamcrest-php              v2.0.0     This is the PHP port of Hamcrest Matchers
hoa/consistency                    2.17.08.29 The Hoa\Consistency library.
hoa/event                          2.17.08.30 The Hoa\Event library.
hoa/exception                      2.17.08.30 The Hoa\Exception library.
league/flysystem                   1.0.44     Filesystem abstraction: Many filesystems, one API.
mockery/mockery                    1.2.0      Mockery is a simple yet flexible PHP mock object framework
myclabs/deep-copy                  1.8.1      Create deep copies (clones) of your objects
nikic/php-parser                   v4.2.0     A PHP parser written in PHP
phar-io/manifest                   1.0.3      Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1      Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1      Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0      With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        0.4.0     
phpspec/prophecy                   1.8.0      Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          6.1.4      Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          2.0.2      FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1      Simple template engine.
phpunit/php-timer                  2.0.0      Utility class for timing
phpunit/php-token-stream           3.0.1      Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.5.2      The PHP Unit Testing framework.
roave/better-reflection            3.2.0      Better Reflection - an improved code reflection API
roave/signature                    1.0.0      Sign and verify stuff
sebastian/code-unit-reverse-lookup 1.0.1      Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2      Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.1      Diff implementation
sebastian/environment              4.0.1      Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0      Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0      Snapshotting of global state
sebastian/object-enumerator        3.0.3      Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1      Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0      Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1      Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1      Library that helps with managing the version number of Git-hosted PHP projects
symfony/polyfill-ctype             v1.10.0    Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.10.0    Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.10.0    Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/var-dumper                 v4.2.2     Symfony mechanism for exploring and dumping PHP variables
theseer/tokenizer                  1.1.0      A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.4.0      Assertions to validate method input/output with nice error messages.
zendframework/zend-code            3.3.1      provides facilities to generate arbitrary code using an object oriented interface
zendframework/zend-eventmanager    3.2.1      Trigger and listen to events within a PHP application
```

Thanks!

**Comment by sebastianbergmann** [comment]
Please only report issues for stable versions of PHPUnit.

**Comment by panosru** [comment]
@sebastianbergmann I have updated to latest stable `7.5.2`, same result. I have updated my original post.

Thanks!

**Comment by panosru** [comment]
@sebastianbergmann I have done it here: https://github.com/panosru/phpunit-debug

you can run:
```
git clone https://github.com/panosru/phpunit-debug.git && cd phpunit-debug && composer install && ./vendor/bin/phpunit
```

The result I got:
```
PHPUnit 7.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.8 with Xdebug 2.7.0alpha1
Configuration: /***/phpunit-debug/phpunit.xml.dist

FooBarUnitTest\Bar
.E                                                                  2 / 2 (100%) [x] Foobar with valid value
 [ ] Foobar with invalid value



Time: 800 ms, Memory: 6.00MB

There was 1 error:

1) FooBarUnitTest\BarTest::foobarWithInvalidValue
PHPUnit\Framework\Exception: Fatal error: Uncaught SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available in /***/phpunit-debug/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:897
Stack trace:
#0 /***/phpunit-debug/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(146): SebastianBergmann\CodeCoverage\CodeCoverage->selectDriver(Object(SebastianBergmann\CodeCoverage\Filter))
#1 Standard input code(409): SebastianBergmann\CodeCoverage\CodeCoverage->__construct(NULL, Object(SebastianBergmann\CodeCoverage\Filter))
#2 Standard input code(584): __phpunit_run_isolated_test()
#3 {main}
  thrown in /***/phpunit-debug/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 897

ERRORS!
Tests: 2, Assertions: 1, Errors: 1.

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done

Generating code coverage report in PHP format ... done
```

**Comment by panosru** [comment]
@sebastianbergmann To add more info to the topic,

My development environment is on MacOS (10.13.6), I have installed MAMP, and I'm using MAMP's PHP version as the default:

![image](https://user-images.githubusercontent.com/400362/51482198-77980300-1d9e-11e9-94e5-96d2cf161e62.png)

MacOS has a built-in PHP binary, do you think it might be conflicting with PHPUnit isolated test runs? From what I see, PHPUnit bin file uses `#!/usr/bin/env php`, shouldn't it use the same binary for isolated tests? Could you please tell me a way to detect which PHP binary the isolated test is using?

I run `git clone https://github.com/panosru/phpunit-debug.git && cd phpunit-debug && composer install && ./vendor/bin/phpunit` on a Docker container, and I got no issues, but my development environment is MacOS, not the docker container so from what I can see, it's not that the code coverage of PHPUnit is broken when using isolated tests, it is that is broken on MacOS specifically I guess.

This is the result of the Docker container:
![image](https://user-images.githubusercontent.com/400362/51482423-11f84680-1d9f-11e9-801d-3fd8742a124b.png)

I would appreciate it if you do not close the issue and provide some insights on how to determine which PHP binary is used for isolated tests.

Thanks!
