### ISSUE TITLE
Test Failure

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit#3504]
While working to release PHPUnit 8.0.0, `/usr/local/src/phpunit/tests/end-to-end/requires-skip-code-location-hints.phpt` suddenly started failing:

```
1) /usr/local/src/phpunit/tests/end-to-end/requires-skip-code-location-hints.phpt
Failed asserting that string matches format description.
--- Expected
+++ Actual
@@ @@
 PHPUnit 7.5.3-243-g502f8bd96 by Sebastian Bergmann and contributors.
 
-RRRRRRRRSSSSSRRRRSSSSRSSSSSSSRRSSSSSSSRRSSSSSSSSSSSSSSSSSSSWWS    62 / 62 (100%)
+RRRRRRRRSSSSSRRRRSSSSRSSSSSSSRRSSSSSSSRRSSSSSSSSSSSSSSSSRSSWWS    62 / 62 (100%)
 
 Time: 28 ms, Memory: 6.00MB
 
@@ @@
 
 1) RequirementsTest::testVersionConstraintInvalidPhpConstraint
 Version constraint ~^12345 is not supported.
-%a
+
+Caused by
+PharIo\Version\UnsupportedVersionConstraintException: Version constraint ~^12345 is not supported. in /usr/local/src/phpunit/vendor/phar-io/version/src/VersionConstraintParser.php:28
+Stack trace:
+#0 /usr/local/src/phpunit/src/Util/Test.php(212): PharIo\Version\VersionConstraintParser->parse('~^12345')
+#1 /usr/local/src/phpunit/src/Util/Test.php(178): PHPUnit\Util\Test::parseRequirements('/**\n     * @req...', 465, Array)
+#2 /usr/local/src/phpunit/src/Util/Test.php(261): PHPUnit\Util\Test::getRequirements('RequirementsTes...', 'testVersionCons...')
+#3 /usr/local/src/phpunit/src/Framework/TestCase.php(1657): PHPUnit\Util\Test::getMissingRequirements('RequirementsTes...', 'testVersionCons...')
+#4 /usr/local/src/phpunit/src/Framework/TestCase.php(826): PHPUnit\Framework\TestCase->checkRequirements()
+#5 /usr/local/src/phpunit/src/Framework/TestResult.php(685): PHPUnit\Framework\TestCase->runBare()
+#6 /usr/local/src/phpunit/src/Framework/TestCase.php(797): PHPUnit\Framework\TestResult->run(Object(RequirementsTest))
+#7 /usr/local/src/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
+#8 /usr/local/src/phpunit/src/TextUI/TestRunner.php(632): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
+#9 /usr/local/src/phpunit/src/TextUI/Command.php(208): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
+#10 /usr/local/src/phpunit/src/TextUI/Command.php(164): PHPUnit\TextUI\Command->run(Array, true)
+#11 Standard input code(11): PHPUnit\TextUI\Command::main()
+#12 {main}
 2) RequirementsTest::testVersionConstraintInvalidPhpUnitConstraint
 Version constraint ~^12345 is not supported.
+
+Caused by
+PharIo\Version\UnsupportedVersionConstraintException: Version constraint ~^12345 is not supported. in /usr/local/src/phpunit/vendor/phar-io/version/src/VersionConstraintParser.php:28
 Stack trace:
+#0 /usr/local/src/phpunit/src/Util/Test.php(212): PharIo\Version\VersionConstraintParser->parse('~^12345')
+#1 /usr/local/src/phpunit/src/Util/Test.php(178): PHPUnit\Util\Test::parseRequirements('/**\n     * @req...', 472, Array)
+#2 /usr/local/src/phpunit/src/Util/Test.php(261): PHPUnit\Util\Test::getRequirements('RequirementsTes...', 'testVersionCons...')
+#3 /usr/local/src/phpunit/src/Framework/TestCase.php(1657): PHPUnit\Util\Test::getMissingRequirements('RequirementsTes...', 'testVersionCons...')
+#4 /usr/local/src/phpunit/src/Framework/TestCase.php(826): PHPUnit\Framework\TestCase->checkRequirements()
+#5 /usr/local/src/phpunit/src/Framework/TestResult.php(685): PHPUnit\Framework\TestCase->runBare()
+#6 /usr/local/src/phpunit/src/Framework/TestCase.php(797): PHPUnit\Framework\TestResult->run(Object(RequirementsTest))
+#7 /usr/local/src/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
+#8 /usr/local/src/phpunit/src/TextUI/TestRunner.php(632): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
+#9 /usr/local/src/phpunit/src/TextUI/Command.php(208): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
+#10 /usr/local/src/phpunit/src/TextUI/Command.php(164): PHPUnit\TextUI\Command->run(Array, true)
+#11 Standard input code(11): PHPUnit\TextUI\Command::main()
+#12 {main}
 --
 
-There were 17 risky tests:
+There were 18 risky tests:
 
 1) RequirementsTest::testOne
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:14
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:14
 
 2) RequirementsTest::testTwo
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:21
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:21
 
 3) RequirementsTest::testThree
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:28
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:28
 
 4) RequirementsTest::testFour
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:36
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:36
 
 5) RequirementsTest::testFive
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:43
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:43
 
 6) RequirementsTest::testSix
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:50
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:50
 
 7) RequirementsTest::testSeven
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:57
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:57
 
 8) RequirementsTest::testEight
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:64
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:64
 
 9) RequirementsTest::testExistingFunction
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:117
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:117
 
 10) RequirementsTest::testExistingMethod
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:124
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:124
 
 11) RequirementsTest::testExistingExtension
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:131
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:131
 
 12) RequirementsTest::testExistingOs
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:138
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:138
 
 13) RequirementsTest::testSpace
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:174
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:174
 
 14) RequirementsTest::testPHPVersionOperatorBangEquals
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:237
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:237
 
 15) RequirementsTest::testPHPVersionOperatorNotEquals
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:245
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:245
 
 16) RequirementsTest::testPHPUnitVersionOperatorBangEquals
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:309
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:309
 
 17) RequirementsTest::testPHPUnitVersionOperatorNotEquals
 This test did not perform any assertions
 
-%stests%e_files%eRequirementsTest.php:317
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:317
 
+18) RequirementsTest::testVersionConstraintTildeOrCaret
+This test did not perform any assertions
+
+/usr/local/src/phpunit/tests/_files/RequirementsTest.php:444
+
 WARNINGS!
-Tests: 62, Assertions: 0, Warnings: 2, Skipped: 43, Risky: 17.
+Tests: 62, Assertions: 0, Warnings: 2, Skipped: 42, Risky: 18.

/usr/local/src/phpunit/tests/end-to-end/requires-skip-code-location-hints.phpt:18
/usr/local/src/phpunit/src/Framework/TestSuite.php:761
/usr/local/src/phpunit/src/Framework/TestSuite.php:761
/usr/local/src/phpunit/src/TextUI/TestRunner.php:632
/usr/local/src/phpunit/src/TextUI/Command.php:208
/usr/local/src/phpunit/src/TextUI/Command.php:164
```

@epdenouden Can you have a look, please?

**Comment by epdenouden** [comment]
That is really weird. Will fix it today. Btw, the output is from 7.5.3 it says. Same for 8.x?

**Comment by epdenouden** [comment]
So far I have no answer, I tried:
- only `RequirementsTest` and the whole collection
- with and without prettified output
- my own and your fork

The failing tests are the only two that test **invalid** version constraint:
- `testVersionConstraintInvalidPhpConstraint`
- `testVersionConstraintInvalidPhpUnitConstraint`

```
 ~/proj/sbergmann-phpunit > 130104cf 8.0.0 > ./phpunit --testdox tests/_files/RequirementsTest.php
[...]
Tests: 62, Assertions: 0, Warnings: 2, Skipped: 43, Risky: 17.
```

```
Tests: 62, Assertions: 0, Warnings: 2, Skipped: 43, Risky: 17.
 ~/proj/phpunit > master 8.0.0 >                                                                                                                                         
```

I'd almost think the `UnsupportedVersionConstraintException` was caught like the other exceptions bubbling up. But why...

**Comment by epdenouden** [comment]
Not sure what's up yet, but _something_ is different with the exception handling of invalid version constraints. In the current output they are seen as warnings, not skipped, and also do not have a location hint.

The error you seems to be related to exception handling or masking. I will investigate further around lunchtime. So weird this suddenly pops up. Do you have any tooling, temporary edits or other open development where you tested this?

Thanks for finding a location hint I missed though 🔬

**Comment by epdenouden** [comment]
@sebastianbergmann Do you have a way of reproducing this? I tried the following:
```
mkdir /tmp
git clone git@github.com:sebastianbergmann/phpunit.git phpunit-v8
cd phpunit-v8
composer update
./phpunit

[...]
OK, but incomplete, skipped, or risky tests!
Tests: 1934, Assertions: 3286, Skipped: 4.
```

**Comment by epdenouden** [comment]
I will make a pull request for a better catching mechanism for these exception, so we can show code location hints and friendlier 'skip' status. Other than that I cannot reproduce the fatal error :(

**Comment by sebastianbergmann** [comment]
I can no longer reproduce this.
