### ISSUE TITLE
PHP options should be passed to child processes

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/phpunit#3506]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 8.0.0
| PHP version         | 7.2.14
| Installation Method | Composer

Playing with pcov...

When enabled (in php.ini), everything OK
```
$ php vendor/bin/phpunit 
PHPUnit 8.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.14 with PCOV 1.0.0
Configuration: /work/GIT/sql-parser/phpunit.xml.dist
```

When disabled globally, and only enabled in command line, it fails

```
$ php -d pcov.enabled=1 vendor/bin/phpunit 
PHPUnit 8.0.0 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.14 with PCOV 1.0.0
Configuration: /work/GIT/sql-parser/phpunit.xml.dist

.....................................II.................EW.....  63 / 545 ( 11%)

```

With some errors like: "_No code coverage driver available_"
```
1) PhpMyAdmin\SqlParser\Tests\Parser\ComponentTest::testParse
PHPUnit\Framework\Exception: Fatal error: Uncaught SebastianBergmann\CodeCoverage\RuntimeException: No code coverage driver available in /work/GIT/sql-parser/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:898
Stack trace:
#0 /work/GIT/sql-parser/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(147): SebastianBergmann\CodeCoverage\CodeCoverage->selectDriver(Object(SebastianBergmann\CodeCoverage\Filter))
#1 Standard input code(40): SebastianBergmann\CodeCoverage\CodeCoverage->__construct(NULL, Object(SebastianBergmann\CodeCoverage\Filter))
#2 Standard input code(112): __phpunit_run_isolated_test()
#3 {main}
  thrown in /work/GIT/sql-parser/vendor/phpunit/php-code-coverage/src/CodeCoverage.php on line 898

Caused by
ErrorException: unserialize(): Error at offset 0 of 696 bytes in /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:254
Stack trace:
#0 [internal function]: PHPUnit\Util\PHP\AbstractPhpProcess->PHPUnit\Util\PHP\{closure}(8, 'unserialize(): ...', '/work/GIT/sql-p...', 254, Array)
#1 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(254): unserialize('\nFatal error: U...')
#2 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(170): PHPUnit\Util\PHP\AbstractPhpProcess->processChildResult(Object(PhpMyAdmin\SqlParser\Tests\Parser\ComponentTest), Object(PHPUnit\Framework\TestResult), '\nFatal error: U...', '')
#3 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Framework/TestCase.php(795): PHPUnit\Util\PHP\AbstractPhpProcess->runTestJob('<?php\nuse PHPUn...', Object(PhpMyAdmin\SqlParser\Tests\Parser\ComponentTest), Object(PHPUnit\Framework\TestResult))
#4 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#5 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/Framework/TestSuite.php(761): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(632): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/TextUI/Command.php(208): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#9 /work/GIT/sql-parser/vendor/phpunit/phpunit/src/TextUI/Command.php(164): PHPUnit\TextUI\Command->run(Array, true)
#10 /work/GIT/sql-parser/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#11 {main}

```

**Comment by remicollet** [comment]
@krakjoe  FYI

**Comment by krakjoe** [comment]
We're going to need to search argv for -d's ... 

Maybe related to #3492

**Comment by krakjoe** [comment]
Well it's more complicated than searching argv ... thinking ...

**Comment by krakjoe** [comment]
Can't get it from server API either, it strips -d's as it processes them ...

**Comment by krakjoe** [comment]
Something like this in Runtime::getBinary is my first working idea ?

```
	if ($this->hasPCOV()) {
		foreach ([
			"pcov.enabled",
			"pcov.directory",
			"pcov.exclude",
			"pcov.initial.files",
			"pcov.initial.memory",
		] as $config) {
			if (($value = ini_get($config))) {
				$args[] = sprintf("-d%s=%s", $config, $value);
			}
		}

		return sprintf("%s %s", self::$binary, implode(' ', $args));
	}

	if ($this->hasXdebug()) {
		/* not sure what options we need ? */
	}

        return self::$binary;
```

Or we could add some other method to runtime to get args, and call that from AbstractPHPProcess ...

**Comment by krakjoe** [comment]
This may be more forward compatible and supports xdebug too but I still don't love it ...

```
	if ($this->hasPCOV()) {
		$pcov = ini_get_all("pcov");
		$args = [];

		foreach ($pcov as $key => $config) {
			$args[] = sprintf("-d%s=%s", 
				$key, $config["local_value"]);
		}

		return sprintf("%s %s", self::$binary, implode(' ', $args));
	}

	if ($this->hasXdebug()) {
		$xdebug = ini_get_all("xdebug");
		$args = [];

		foreach ($xdebug as $key => $config) {
			$args[] = sprintf("-d%s=%s", 
				$key, $config["local_value"]);
		}

		return sprintf("%s %s", self::$binary, implode(' ', $args));
	}

        return self::$binary;
```

What's odd is the `local_value` and `global_value` from `ini_get_all` seem to be the same all the time ...

**Comment by krakjoe** [comment]
I got another idea, maybe parse out the loaded ini file and only add what doesn't match the ini ?

**Comment by krakjoe** [comment]
So here's what I got, I think this isn't too bad ...

This in Runtime:

```
    public function getCurrentSettings(array $values) : array {
        $diff = [];

        $files = [\php_ini_loaded_file()];
        if ($scanned = \php_ini_scanned_files()) {
            $files = \array_merge($files, $scanned);
        }

        foreach ($files as $ini) {
            $config = \parse_ini_file($ini, true);

            foreach ($values as $value) {
                $set = \ini_get($value);

                if (isset($config[$value]) && $set != $config[$value]) {
                    $diff[] = sprintf("%s=%s", $value, $set);
                }
            }
        }

        return $diff;
    }
```

and this in AbstractPhpProcess::getCommand

```
    public function getCommand(array $settings, string $file = null): string
    {
        $command = $this->runtime->getBinary();

	if ($this->runtime->hasPCOV()) {
            $pcov = $this->runtime->getCurrentSettings(
		\array_keys(\ini_get_all("pcov")));
            $settings = \array_merge($settings, $pcov);
        } else if ($this->runtime->hasXdebug()) {
            $xdebug = $this->runtime->getCurrentSettings(
                \array_keys(\ini_get_all("xdebug")));
            $settings = array_merge($settings, $xdebug);
        }

        $command .= $this->settingsToParameters($settings);
```

This is working for xdebug and pcov ...

Any thoughts ?

**Comment by remicollet** [comment]
For Pcov, "production" default is enabled=0, and was thinking to use is this way, using the command line option.

For XDebug, this is a bit different, as there is no "enable" option (may have to be enable using -d zend_extension=xdebug, but this can be another issue because of extension load order).

**Comment by krakjoe** [comment]
There is `coverage_enable` in xdebug too

**Comment by krakjoe** [comment]
@sebastianbergmann can we get some input on this please ?

**Comment by sebastianbergmann** [comment]
Child processes currently do not "inherit" PHP options. They probably should. https://github.com/sebastianbergmann/phpunit/issues/3506#issuecomment-459810795 is hard for me to look at / review / judge. A pull request would make it a lot easier for me to review what you propose.

**Comment by krakjoe** [comment]
ack, will do pulls ...

**Comment by sebastianbergmann** [comment]
Thanks! And sorry for dropping the ball on this.

**Comment by sebastianbergmann** [comment]
@krakjoe Did you get a chance to work on this yet? Thanks!

**Comment by christianjbrown** [comment]
Just wanted to double check - this is fixed in PHP Unit 9 because it uses a later version of sebastian/environment that has the fix?

No chance of a fix for 8.5?

**Comment by sebastianbergmann** [comment]
AFAICS, https://github.com/sebastianbergmann/environment/pull/36/commits/61420aab40a6ff2bdbcfb1e32656a2d5b04ee927 is in version 4.2.0 and up of this component. And 4.x is what PHPUnit 8.5 uses.

**Comment by christianjbrown** [comment]
I think we can confirm this is still occurring in PHPUnit 8.5. Command line PHP options, ie -d options, are not being passed on to tests that have @runInSeparateProcess.

Maybe it's more specifically #3492, the d=xdebug.so is not passing on. Worth reopening that ticket or this more generic one?

**Comment by robsontenorio** [comment]
Just opened a new issue. It is not working for me. Could you confirm?
