### ISSUE TITLE
Uncaught Exception: Serialization of 'Closure' is not allowed in GlobalState.php

### ISSUE THREAD

**Issue by Proxxx23** [sebastianbergmann/phpunit#3934]
If I run a bunch of tests, some test classes fails because of exception:

```
Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php on line 158

PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php:158
Exception: Serialization of 'Closure' is not allowed in /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php on line 158
Stack trace:

Call Stack:
#0 /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php(158): serialize(Array)
    0.0001     409192   1. {main}() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/phpunit:0
    0.0128    2408736   2. PHPUnit\TextUI\Command::main() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/phpunit:61
#1 /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php(143): PHPUnit\Util\GlobalState::exportVariable(Array)
    0.0128    2408848   3. PHPUnit\TextUI\Command->run() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/TextUI/Command.php:159
#2 /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestCase.php(663): PHPUnit\Util\GlobalState::getGlobalsAsString()
    0.0917    7584928   4. PHPUnit\TextUI\TestRunner->doRun() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/TextUI/Command.php:200
#3 /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(569): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
    0.1134    8148656   5. PHPUnit\Framework\TestSuite->run() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:616
#4 /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php(569): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
    4.3367   58852288   6. PHPUnit\Framework\TestSuite->run() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:569
    4.3375   58854792   7. PHPUnit\Framework\DataProviderTestSuite->run() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:569
#5 /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/ in /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php on line 158
    4.3376   58854984   8. Tests\NwtUnit\Utils\LocationTest->run() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:569
    4.3383   58880104   9. PHPUnit\Util\GlobalState::getGlobalsAsString() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Framework/TestCase.php:663
    4.3386   58901016  10. PHPUnit\Util\GlobalState::exportVariable() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php:143
    4.3386   58901016  11. serialize() /home/lukasz/PhpstormProjects/everyware/www/vendor/phpunit/phpunit/src/Util/GlobalState.php:158

Process finished with exit code 255
```

The thing is, if I run this test class standalone, it works like charm. This exception appears randomly after 60-80 tests performed. It is not related to any specific test class. 

PHPUnit 8.4.3

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by Proxxx23** [comment]
It's hard to provide such test case, as I have bunch of tests and those fail only if run in a set. If I run them one by one, nothing wrong tooks place. But if I run a set, then one of the test classes crashes randomously.

**Comment by sebastianbergmann** [comment]
Then I cannot help you, sorry.

**Comment by epdenouden** [comment]
Hi @Proxxx23 !

I notice this happens during while running a dataprovider test. By any chance, is something running out of memory, storage or time(out)?

Or, are they interdependencies between the data rows that you have yet to discover?

That's the kind of issue I keep finding when working on the execution reordering and dataprovider features of phpunit

**Comment by Proxxx23** [comment]
Will check it out, thanks, but the weirdest thing is it didn't happen before :(

**Comment by Chrishow2** [comment]
@Proxxx23 I'm having the exact same problem when running just two very basic tests each with @runInSeparateProcess. Did you manage to solve this?
