### ISSUE TITLE
Class name must be a valid object or a string in phpunit/php-token-stream/src/Token/Stream.php

### ISSUE THREAD

**Issue by mmartinello** [sebastianbergmann/phpunit#3944]
I'm receiving this error when executing phpunit with code coverage enabled:

```
⨯ ./phpunit tests/                                                                                     16:34:04
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.11 with Xdebug 2.8.0
Configuration: /Users/me/Projects/foo/phpunit.xml

.....                                                               5 / 5 (100%)

Time: 14.87 seconds, Memory: 118.01MB

OK (5 tests, 29 assertions)

Generating code coverage report in Clover XML format ...PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /Users/me/Projects/foo/vendor/phpunit/php-token-stream/src/Token/Stream.php:189
Stack trace:
#0 /Users/me/Projects/foo/vendor/phpunit/php-token-stream/src/Token/Stream.php(118): PHP_Token_Stream->scan('#!/usr/bin/php\n...')
#1 /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(764): PHP_Token_Stream->__construct('#!/usr/bin/php\n...')
#2 /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(673): SebastianBergmann\CodeCoverage\CodeCoverage->getLinesToBeIgnored('/Users/me/P...')
#3 /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(321): SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter(Array)
#4 /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(722): SebastianBergmann\CodeCoverage\CodeCoverage->append(Array, 'UNCOVERED_FILES...')
#5 /Users/ in /Users/me/Projects/foo/vendor/phpunit/php-token-stream/src/Token/Stream.php on line 189

Fatal error: Uncaught Error: Class name must be a valid object or a string in /Users/me/Projects/foo/vendor/phpunit/php-token-stream/src/Token/Stream.php on line 189

Error: Class name must be a valid object or a string in /Users/me/Projects/foo/vendor/phpunit/php-token-stream/src/Token/Stream.php on line 189

Call Stack:
    0.0004     397016   1. {main}() /Users/me/Projects/foo/vendor/phpunit/phpunit/phpunit:0
    0.0231    1461848   2. PHPUnit_TextUI_Command::main() /Users/me/Projects/foo/vendor/phpunit/phpunit/phpunit:52
    0.0231    1461960   3. PHPUnit_TextUI_Command->run() /Users/me/Projects/foo/vendor/phpunit/phpunit/src/TextUI/Command.php:116
    0.4424   14570176   4. PHPUnit_TextUI_TestRunner->doRun() /Users/me/Projects/foo/vendor/phpunit/phpunit/src/TextUI/Command.php:186
   14.8791   35999128   5. SebastianBergmann\CodeCoverage\Report\Clover->process() /Users/me/Projects/foo/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:534
   14.8792   35999456   6. SebastianBergmann\CodeCoverage\CodeCoverage->getReport() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/Report/Clover.php:47
   14.8795   36025272   7. SebastianBergmann\CodeCoverage\Node\Builder->build() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:163
   14.8795   36025272   8. SebastianBergmann\CodeCoverage\CodeCoverage->getData() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/Node/Builder.php:24
   14.8795   36025272   9. SebastianBergmann\CodeCoverage\CodeCoverage->addUncoveredFilesFromWhitelist() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:198
   15.1846   45029880  10. SebastianBergmann\CodeCoverage\CodeCoverage->append() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:722
   15.2026   45029904  11. SebastianBergmann\CodeCoverage\CodeCoverage->applyIgnoredLinesFilter() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:321
   15.8821   39247248  12. SebastianBergmann\CodeCoverage\CodeCoverage->getLinesToBeIgnored() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:673
   15.8847   39546136  13. PHP_Token_Stream->__construct() /Users/me/Projects/foo/vendor/phpunit/php-code-coverage/src/CodeCoverage.php:764
   15.8848   39615768  14. PHP_Token_Stream->scan() /Users/me/Projects/foo/vendor/phpunit/php-token-stream/src/Token/Stream.php:118
```

My composer.json file (I need to keep PHP 5.6 compatibility, but I'm running with PHP 7.3 here):
```
{
    "require": {
        "php": ">=5.6.0",
        "monolog/monolog": "1.*"
    },
    "require-dev": {
        "phpunit/phpunit": "5.7.27",
        "phpdocumentor/phpdocumentor": "2.*",
        "sebastian/phpcpd": "2.*",
        "phpunit/php-token-stream": "1.4.12"
    }
}
```

My phpunit.xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://phpunit.de/phpunit.xsd"
        backupGlobals="false"
        bootstrap="vendor/autoload.php"
        colors="true"
        verbose="true">
  <testsuite name="main">
    <directory suffix="Test.php">tests</directory>
  </testsuite>

  <logging>
    <log type="coverage-text" target="php://stdout"/>
    <log type="coverage-clover" target="cov.xml"/>
  </logging>

  <filter>
    <whitelist processUncoveredFilesFromWhitelist="false">
      <directory suffix=".php">_classes</directory>
    </whitelist>
  </filter>
</phpunit>
```

**Comment by sebastianbergmann** [comment]
PHPUnit 5.7 is no longer supported. Please open a new ticket in case this still applies to a supported version of PHPUnit.
