### ISSUE TITLE
Numeric group names are not handled correctly

### ISSUE THREAD

**Issue by beberlei** [sebastianbergmann/phpunit#4489]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4
| PHP version         | 8.0-RC1
| Installation Method | Composer

#### Summary

Exception during phpunit startup:

```
PHP Fatal error:  Uncaught TypeError: strpos(): Argument #1 ($haystack) must be of type string, int given in /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php:900
Stack trace:
#0 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(900): strpos()
#1 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(287): PHPUnit\Framework\TestSuite->containsOnlyVirtualGroups()
#2 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(365): PHPUnit\Framework\TestSuite->addTest()
#3 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(504): PHPUnit\Framework\TestSuite->addTestSuite()
#4 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/Framework/TestSuite.php(529): PHPUnit\Framework\TestSuite->addTestFile()
#5 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/TestSuite/TestSuiteMapper.php(50): PHPUnit\Framework\TestSuite->addTestFiles()
#6 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/TextUI/Command.php(389): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map()
#7 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/TextUI/Command.php(116): PHPUnit\TextUI\Command->handleArguments()
#8 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/src/TextUI/Command.php(101): PHPUnit\TextUI\Command->run()
#9 /home/benny/code/workspace/github.com/doctrine/orm/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#10 {main}
```

Caused by a test using only a number as group:

```
/**
 * @group 6759
 */
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by boesing** [comment]
```
final class FooTest extends \PHPUnit\Framework\TestCase 
{
    /** @group 12345 */
    public function testFoo(): void
    {}
}
```

In `TestSuite::containsOnlyVirtualGroups`, all groups are checked with `strpos` and in `TestSuite::getGroups` `array_keys` is being used. Integerish array keys (even if they are passed as strings) are [interpreted as integers](https://3v4l.org/Y2ld5).

**Comment by sebastianbergmann** [comment]
I am still not able to reproduce this:
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class Issue4489Test extends TestCase 
{
    /**
     * @group 12345
     */
    public function testOne(): void
    {
        $this->assertTrue(true);
    }
}
```
$ phpunit Issue4489Test.php
PHPUnit 9.4.3-8-gf1649d0b1 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.018, Memory: 4.00 MB

OK (1 test, 1 assertion)
```
```
$ phpunit --group 12345 Issue4489Test.php
PHPUnit 9.4.3-8-gf1649d0b1 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.018, Memory: 4.00 MB

OK (1 test, 1 assertion)
```
```
$ phpunit --group 1234 Issue4489Test.php
PHPUnit 9.4.3-8-gf1649d0b1 by Sebastian Bergmann and contributors.

No tests executed!
```

**Comment by sebastianbergmann** [comment]
Nevermind, using `--list-groups` I can trigger it:
```
`$ phpunit --list-groups Issue4489Test.php 
PHPUnit 9.4.3-8-gf1649d0b1 by Sebastian Bergmann and contributors.

Available test group(s):

Fatal error: Uncaught TypeError: strpos() expects parameter 1 to be string, int given in /usr/local/src/phpunit/src/TextUI/Command.php:655
Stack trace:
#0 /usr/local/src/phpunit/src/TextUI/Command.php(655): strpos(12345, '__phpunit_')
#1 /usr/local/src/phpunit/src/TextUI/Command.php(130): PHPUnit\TextUI\Command->handleListGroups(Object(PHPUnit\Framework\TestSuite), true)
#2 /usr/local/src/phpunit/src/TextUI/Command.php(101): PHPUnit\TextUI\Command->run(Array, true)
#3 /usr/local/src/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#4 {main}

Next PHPUnit\TextUI\Exception: strpos() expects parameter 1 to be string, int given in /usr/local/src/phpunit/src/TextUI/Command.php:103
Stack trace:
#0 /usr/local/src/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#1 {main}
  thrown in /usr/local/src/phpunit/src/TextUI/Command.php on line 103
```

This does not explain @beberlei's "during phpunit startup" aspect, though.

**Comment by boesing** [comment]
We've had the same issue in laminas tests. It only appeared on PHP 8 during start up even without adding any group Argument to the runner. 🤷🏼‍♂️

Did not dig deeper tbh, just had a quick dive to understand what is happening and not why its only on PHP 8.
