### ISSUE TITLE
Upgrading from Phpunit 9.3 to 9.4 cause weird issue with Phpstan.

### ISSUE THREAD

**Issue by VincentLanglet** [sebastianbergmann/phpunit#4500]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.4.2
| PHP version         | 7.4
| Installation Method | Phpunit bridge

#### Summary

When running
```
php -d memory_limit=-1 ./vendor/bin/phpstan --error-format=checkstyle analyse -l 5 -c phpstan.neon.dist --debug
```

I get the following issue (and [I'm not the only one](https://github.com/getsentry/sentry-symfony/issues/383#issuecomment-717299643))
```
Fatal error: Uncaught OutOfBoundsException: Package "project/project" is not installed in /app/payment/bin/.phpunit/phpunit-9-0/vendor/composer/InstalledVersions.php:451
Stack trace:
#0 /app/payment/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php(254): Composer\InstalledVersions::getPrettyVersion('platform/paymen...')
#1 /app/payment/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(13): PackageVersions\Versions::getVersion('platform/paymen...')
#2 /app/payment/vendor/jean85/pretty-package-versions/src/PrettyVersions.php(23): Jean85\PrettyVersions::getVersion('platform/paymen...')
#3 /app/payment/vendor/sentry/sentry-symfony/src/DependencyInjection/Configuration.php(117): Jean85\PrettyVersions::getRootPackageVersion()
#4 /app/payment/vendor/symfony/config/Definition/Processor.php(50): Sentry\SentryBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#5 /app/payment/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Proc in /app/payment/bin/.phpunit/phpunit-9-0/vendor/composer/InstalledVersions.php on line 451
```

I'm using the symfony phpunit bridge.
Previously I was using the config variable 
```
<server name="SYMFONY_PHPUNIT_VERSION" value="9" />
```
Which was installing the 9.4 version. If I fix this to `9.3` instead, I don't have the error anymore.

I don't know if it's more phpstan related or phpunit related.
So I also created https://github.com/phpstan/phpstan/issues/4022

**Comment by sebastianbergmann** [comment]
Please report issues related to Symfony's PHPUnit bridge to the Symfony project.
