### ISSUE TITLE
Exception stack trace thrown from extension before first test is not displayed for 9.5.x versions

### ISSUE THREAD

**Issue by andrew-demb** [sebastianbergmann/phpunit#4606]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.2
| PHP version         | 7.4.15
| Installation Method | Composer

#### Summary

Exception stack trace thrown from extension (which subscribes before first test) is not displayed.

Output for PHPUnit 9.4.4:
```
./vendor/bin/phpunit
PHPUnit 9.4.4 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught RuntimeException: Cannot connect to external system in /src/phpunit-issue/src/PhpUnit/ExceptionExtension.php:12
Stack trace:
#0 /src/phpunit-issue/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): Issue\PhpUnit\ExceptionExtension->executeBeforeFirstTest()
#1 /src/phpunit-issue/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\TestRunner->run()
#2 /src/phpunit-issue/vendor/phpunit/phpunit/src/TextUI/Command.php(101): PHPUnit\TextUI\Command->run()
#3 /src/phpunit-issue/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#4 {main}

Next PHPUnit\TextUI\Exception: Cannot connect to external system in /src/phpunit-issue/vendor/phpunit/phpunit/src/TextUI/Command.php:103
Stack trace:
#0 /src/phpunit-issue/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::ma in /src/phpunit-issue/vendor/phpunit/phpunit/src/TextUI/Command.php on line 103
```

#### Current behavior

No exception stack trace in output.
```
./vendor/bin/phpunit
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

Cannot connect to external system
```

#### How to reproduce

Config (phpunit.xml):
```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.5/phpunit.xsd"
         bootstrap="vendor/autoload.php"
>
    <testsuites>
        <testsuite name="Project Test Suite">
            <directory>tests/</directory>
        </testsuite>
    </testsuites>

    <extensions>
        <extension class="Issue\PhpUnit\ExceptionExtension"/>
    </extensions>
</phpunit>
```

Extension with exception (src/PhpUnit/ExceptionExtension.php):
```php
<?php
namespace Issue\PhpUnit;

use PHPUnit\Runner\BeforeFirstTestHook;

class ExceptionExtension implements BeforeFirstTestHook
{
    public function executeBeforeFirstTest(): void
    {
        throw new \RuntimeException('Cannot connect to external system');
    }
}
```

composer.json
```json
{
    "type": "library",
    "autoload": {
        "psr-4": {
            "Issue\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Issue\\": "tests/"
        }
    },
    "require": {
        "php": "^7.2.0",
        "phpunit/phpunit": "^9.0"
    }
}
```

Output of `composer show | sort`
```
doctrine/instantiator              1.4.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
myclabs/deep-copy                  1.10.2  Create deep copies (clones) of your objects
nikic/php-parser                   v4.10.4 A PHP parser written in PHP
phar-io/manifest                   2.0.1   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    3.0.4   Library for handling version information and constraints
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  5.2.2   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver        1.4.0   A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                   1.12.2  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          9.2.5   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          3.0.5   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                3.1.1   Invoke callables with a timeout
phpunit/php-text-template          2.0.4   Simple template engine.
phpunit/php-timer                  5.0.3   Utility class for timing
phpunit/phpunit                    9.5.2   The PHP Unit Testing framework.
sebastian/cli-parser               1.0.1   Library for parsing CLI options
sebastian/code-unit                1.0.8   Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup 2.0.3   Looks up which function or method a line of code belongs to
sebastian/comparator               4.0.6   Provides the functionality to compare PHP values for equality
sebastian/complexity               2.0.2   Library for calculating the complexity of PHP code units
sebastian/diff                     4.0.4   Diff implementation
sebastian/environment              5.1.3   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 4.0.3   Provides the functionality to export PHP variables for visualization
sebastian/global-state             5.0.2   Snapshotting of global state
sebastian/lines-of-code            1.0.3   Library for counting the lines of code in PHP source code
sebastian/object-enumerator        4.0.4   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         2.0.4   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        4.0.4   Provides functionality to recursively process PHP variables
sebastian/resource-operations      3.0.3   Provides a list of PHP built-in functions that operate on resources
sebastian/type                     2.3.1   Collection of value objects that represent the types of the PHP type system
sebastian/version                  3.0.2   Library that helps with managing the version number of Git-hosted PHP projects
symfony/polyfill-ctype             v1.22.1 Symfony polyfill for ctype functions
theseer/tokenizer                  1.2.0   A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.9.1   Assertions to validate method input/output with nice error messages.
```

#### Expected behavior

Exception class and stack trace is shown.

**Comment by sebastianbergmann** [comment]
Does this problem still exist in PHPUnit 9.6 or PHPUnit 10.3?

**Comment by andrew-demb** [comment]
I can confirm, that for PHPUnit 9.6 problem still exist.

```bash
./vendor/bin/phpunit
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.

Cannot connect to external system
```

----

For 10.3 - exception from subscriber fully ignored by PHPUnit.

```bash
./vendor/bin/phpunit
PHPUnit 10.3.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.10
Configuration: .../phpunit.xml.dist

.                                                                   1 / 1 (100%)

Time: 00:00.009, Memory: 8.00 MB

OK (1 test, 1 assertion)

```

Example exception class:
```php
<?php

declare(strict_types=1);

namespace Issue\PhpUnit;

use PHPUnit\Event\Application\Started;
use PHPUnit\Event\Application\StartedSubscriber;
use PHPUnit\Runner\Extension\Extension;
use PHPUnit\Runner\Extension\Facade;
use PHPUnit\Runner\Extension\ParameterCollection;
use PHPUnit\TextUI\Configuration\Configuration;

final class ExceptionExtension implements Extension
{
    public function bootstrap(
        Configuration $configuration,
        Facade $facade,
        ParameterCollection $parameters,
    ): void {
        $facade->registerSubscribers(
            new class() implements StartedSubscriber {
                public function notify(Started $event): void
                {
                    throw new \RuntimeException('Cannot connect to external system');
                }
            },
        );
    }
}

```

Example test:
```php
<?php

declare(strict_types=1);

namespace Issue\tests;

use PHPUnit\Framework\TestCase;

final class ExampleTest extends TestCase
{
    public function testSuccess(): void
    {
        $this->assertTrue(true);
    }
}

```

**Comment by sebastianbergmann** [comment]
> exception from subscriber fully ignored by PHPUnit

Starting with PHPUnit 10.4, exceptions thrown by third-party event subscribers will be reported as test runner warnings.

**Comment by sebastianbergmann** [comment]
Fixing this issue for PHPUnit 9.6 requires more changes to the code than I am comfortable to make.
