### ISSUE TITLE
Try to generate configuration on fresh install

### ISSUE THREAD

**Issue by michel-maier** [sebastianbergmann/phpunit#4665]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.4
| PHP version         | 8.0.5
| Installation Method | Composer (v2.0.13)

#### Summary

On a fresh installation with composer require --dev phpunit/phpunit, I cannot generate configuration.

#### Current behavior

When I try to generate configuration according documentation, I have that issue :
```console
$ phpunit --generate-configuration 
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Generating phpunit.xml in /app

Bootstrap script (relative to path shown above; default: vendor/autoload.php): 
Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given in /app/vendor/phpunit/phpunit/src/TextUI/Command.php:734
Stack trace:
#0 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(734): trim(false)
#1 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(227): PHPUnit\TextUI\Command->generateConfiguration()
#2 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments(Array)
#3 /app/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#4 /app/vendor/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#5 {main}

Next PHPUnit\TextUI\RuntimeException: trim(): Argument #1 ($string) must be of type string, bool given in /app/vendor/phpunit/phpunit/src/TextUI/Command.php on line 98

PHPUnit\TextUI\RuntimeException: trim(): Argument #1 ($string) must be of type string, bool given in /app/vendor/phpunit/phpunit/src/TextUI/Command.php on line 98

Call Stack:
    0.0001     394960   1. {main}() /app/vendor/phpunit/phpunit/phpunit:0
    0.0042    1152360   2. PHPUnit\TextUI\Command::main($exit = ???) /app/vendor/phpunit/phpunit/phpunit:61
```

#### How to reproduce

```console
 $ composer require --dev phpunit/phpunit
...

$ bin/phpunit --generate-configuration 
```
In composer file, my config bin-dir is "bin".

#### Expected behavior

The beautifull traditional phpunit.xml.dist file.

**Comment by uuf6429** [comment]
@sebastianbergmann just a note: I get this error when I run phpunit through composer (it might be more convenient on Windows for example).

For example:
```shell
composer exec phpunit -- --generate-configuration   # fails with the same reported error

php vendor/bin/phpunit --generate-configuration     # works
```
