### ISSUE TITLE
migrate-configuration gives "Schema for PHPUnit 9.2 is not available"

### ISSUE THREAD

**Issue by phil-davis** [sebastianbergmann/phpunit#4671]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.4
| PHP version         | 7.4.18
| Installation Method | Composer

#### Summary
Our phpunit is installed by composer in a `lib/composer` directory.
The configuration is in `tests/phpunit-autotest.xml`
When I run tests in CI, I get the problem that "Schema for PHPUnit 9.2 is not available"
When I locally try to convert the xml I also get ""Schema for PHPUnit 9.2 is not available"

#### Current behavior

```
phil@phil-OptiPlex-3050:~/git/owncloud/core$ lib/composer/phpunit/phpunit/phpunit -c tests/phpunit-autotest.xml --migrate-configuration
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

PHP Fatal error:  Uncaught PHPUnit\Util\Xml\Exception: Schema for PHPUnit 9.2 is not available in /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/Util/Xml/SchemaFinder.php:34
Stack trace:
#0 /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/Util/Xml/SchemaDetector.php(30): PHPUnit\Util\Xml\SchemaFinder->find()
#1 /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/TextUI/Command.php(787): PHPUnit\Util\Xml\SchemaDetector->detect()
#2 /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/TextUI/Command.php(325): PHPUnit\TextUI\Command->migrateConfiguration()
#3 /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments()
#4 /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run()
#5 /home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/phpunit(61): PHPUnit\TextUI\Command::main()
#6 {main}
```

#### How to reproduce
Try to use migrate-configuration when installed from composer like above.

#### Expected behavior
migrate-configuration converts the config without crashing.

Note: it is looking for `/home/phil/git/owncloud/core/lib/composer/phpunit/phpunit/src/Util/Xml/../../../schema/9.2.xsd` 
But in `lib/composer/phpunit/phpunit` there is only a `src` directory. There is no `schema` directory.

Maybe this is a problem with the `schema` directory not being "published" to composer.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this:
#### Install PHPUnit 9.2
```
$ composer --ignore-platform-reqs require --dev phpunit/phpunit 9.2.0
./composer.json has been updated
Running composer update phpunit/phpunit
Loading composer repositories with package information
Updating dependencies
Lock file operations: 31 installs, 0 updates, 0 removals
  - Locking doctrine/instantiator (1.4.0)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking phar-io/manifest (1.0.3)
  - Locking phar-io/version (2.0.1)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.2.2)
  - Locking phpdocumentor/type-resolver (1.4.0)
  - Locking phpspec/prophecy (1.13.0)
  - Locking phpunit/php-code-coverage (8.0.2)
  - Locking phpunit/php-file-iterator (3.0.5)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (4.0.0)
  - Locking phpunit/php-token-stream (4.0.4)
  - Locking phpunit/phpunit (9.2.0)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.3)
  - Locking sebastian/global-state (4.0.0)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.1)
  - Locking sebastian/version (3.0.2)
  - Locking symfony/polyfill-ctype (v1.22.1)
  - Locking theseer/tokenizer (1.2.0)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 31 installs, 0 updates, 0 removals
  - Downloading phpunit/php-token-stream (4.0.4)
  - Downloading sebastian/global-state (4.0.0)
  - Downloading phpunit/php-timer (4.0.0)
  - Downloading phpunit/php-code-coverage (8.0.2)
  - Downloading phar-io/version (2.0.1)
  - Downloading phar-io/manifest (1.0.3)
  - Downloading phpunit/phpunit (9.2.0)
  - Installing symfony/polyfill-ctype (v1.22.1): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.4.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.2.2): Extracting archive
  - Installing phpunit/php-token-stream (4.0.4): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.1): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (4.0.0): Extracting archive
  - Installing sebastian/exporter (4.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing phpunit/php-timer (4.0.0): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (8.0.2): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.13.0): Extracting archive
  - Installing phar-io/version (2.0.1): Extracting archive
  - Installing phar-io/manifest (1.0.3): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (9.2.0): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
23 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

#### Generate `phpunit.xml`
```
$ ./vendor/bin/phpunit --generate-configuration                      
PHPUnit 9.2.0 by Sebastian Bergmann and contributors.

Generating phpunit.xml in /home/sb/example

Bootstrap script (relative to path shown above; default: vendor/autoload.php): 
Tests directory (relative to path shown above; default: tests): 
Source directory (relative to path shown above; default: src): 

Generated phpunit.xml in /home/sb/example
```

#### `/home/sb/example/phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.2/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         executionOrder="depends,defects"
         forceCoversAnnotation="true"
         beStrictAboutCoversAnnotation="true"
         beStrictAboutOutputDuringTests="true"
         beStrictAboutTodoAnnotatedTests="true"
         verbose="true">
    <testsuites>
        <testsuite name="default">
            <directory suffix="Test.php">tests</directory>
        </testsuite>
    </testsuites>

    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
        </whitelist>
    </filter>
</phpunit>
```

#### Install PHPUnit 9.5.4
```
$ rm -rf composer.json composer.lock vendor

$ composer require --dev phpunit/phpunit           
Using version ^9.5 for phpunit/phpunit
./composer.json has been created
Running composer update phpunit/phpunit
Loading composer repositories with package information
Updating dependencies
Lock file operations: 34 installs, 0 updates, 0 removals
  - Locking doctrine/instantiator (1.4.0)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking nikic/php-parser (v4.10.5)
  - Locking phar-io/manifest (2.0.1)
  - Locking phar-io/version (3.1.0)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.2.2)
  - Locking phpdocumentor/type-resolver (1.4.0)
  - Locking phpspec/prophecy (1.13.0)
  - Locking phpunit/php-code-coverage (9.2.6)
  - Locking phpunit/php-file-iterator (3.0.5)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking phpunit/phpunit (9.5.4)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.3)
  - Locking sebastian/global-state (5.0.2)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.1)
  - Locking sebastian/version (3.0.2)
  - Locking symfony/polyfill-ctype (v1.22.1)
  - Locking theseer/tokenizer (1.2.0)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 34 installs, 0 updates, 0 removals
  - Installing symfony/polyfill-ctype (v1.22.1): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.4.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.2.2): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing sebastian/type (2.3.1): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.2): Extracting archive
  - Installing sebastian/exporter (4.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.5): Extracting archive
  - Installing theseer/tokenizer (1.2.0): Extracting archive
  - Installing nikic/php-parser (v4.10.5): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.6): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (1.13.0): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.1): Extracting archive
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phpunit/phpunit (9.5.4): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
26 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

#### Migrate configuration
```
$ ./vendor/bin/phpunit --migrate-configuration 
PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

Created backup:         /home/sb/example/phpunit.xml.bak
Migrated configuration: /home/sb/example/phpunit.xml
```

#### `/home/sb/example/phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" bootstrap="vendor/autoload.php" executionOrder="depends,defects" forceCoversAnnotation="true" beStrictAboutCoversAnnotation="true" beStrictAboutOutputDuringTests="true" beStrictAboutTodoAnnotatedTests="true" verbose="true">
  <coverage processUncoveredFiles="true">
    <include>
      <directory suffix=".php">src</directory>
    </include>
  </coverage>
  <testsuites>
    <testsuite name="default">
      <directory suffix="Test.php">tests</directory>
    </testsuite>
  </testsuites>
</phpunit>
```

**Comment by phil-davis** [comment]
Please accept my apologies. `composer.json` had:
```
"dg/composer-cleaner": "^2.1"
```
in it.

That thing has cleaned up the `schema` directory!

When I remove that, then all is good. I will tell `dg/composer-cleaner` to not clean `phpunit`!
