### ISSUE TITLE
Test run via PhpStorm fails on PhpUnit dev-master

### ISSUE THREAD

**Issue by isfedorov** [sebastianbergmann/phpunit#4814]
PHPUnit version => dev-master (10.0)
PHP version       => 8.0.12
Installation Method => Composer 

#### Summary

Hi! PhpStorm team is here. This issue is related to #4699. The problem is that test run via PhpStorm on PhpUnit 10 (dev-master) fails with error 
```
An error occurred inside PHPUnit.

Message:  assert($testSuite instanceof TestSuiteForTestMethodWithDataProvider)
Location: /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Logging/TeamCity/TeamCityLogger.php:94
```
#### Current behavior

Test run fails with next trace
```
/usr/local/Cellar/php/8.0.12/bin/php /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/phpunit --no-configuration /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/tests --teamcity --cache-result-file=/Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/.phpunit.result.cache
Testing started at 11:40 ...


An error occurred inside PHPUnit.

Message:  assert($testSuite instanceof TestSuiteForTestMethodWithDataProvider)
Location: /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Logging/TeamCity/TeamCityLogger.php:94

#0 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Logging/TeamCity/TeamCityLogger.php(94): assert(false, 'assert($testSui...')
#1 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Logging/TeamCity/Subscriber/TestSuiteStartedSubscriber.php(22): PHPUnit\Logging\TeamCity\TeamCityLogger->testSuiteStarted(Object(PHPUnit\Event\TestSuite\Started))
#2 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Event/Dispatcher/DirectDispatcher.php(90): PHPUnit\Logging\TeamCity\TestSuiteStartedSubscriber->notify(Object(PHPUnit\Event\TestSuite\Started))
#3 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Event/Dispatcher/DeferredDispatcher.php(47): PHPUnit\Event\DirectDispatcher->dispatch(Object(PHPUnit\Event\TestSuite\Started))
#4 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Event/Emitter/DispatchingEmitter.php(623): PHPUnit\Event\DeferredDispatcher->dispatch(Object(PHPUnit\Event\TestSuite\Started))
#5 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/Framework/TestSuite.php(412): PHPUnit\Event\DispatchingEmitter->testSuiteStarted(Object(PHPUnit\Event\TestSuite\TestSuiteWithName))
#6 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(407): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/TextUI/Application.php(112): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite))
#8 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/src/TextUI/Application.php(80): PHPUnit\TextUI\Application->run(Array, true)
#9 /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/phpunit(84): PHPUnit\TextUI\Application::main()
#10 {main}

Process finished with exit code 255

```

$testSuite has type `TestSuiteWithName` on assert ` assert($testSuite instanceof TestSuiteForTestMethodWithDataProvider)`
 
<img width="785" alt="Screenshot 2021-11-08 at 11 50 53" src="https://user-images.githubusercontent.com/37301285/140729578-b5fa629f-2bb5-4eaa-93c6-5917ccdcd45d.png">

#### How to reproduce

Steps to reproduce:
Install PHPUnit dev-master using composer.json like below
```
{
  "require": {
    "php": "^8.0",
    "nikic/php-parser": "dev-master as 4.13",
    "phpdocumentor/reflection-docblock": "@stable",
    "sebastian/object-enumerator": "dev-master as 5.0",
    "sebastian/object-reflector": "dev-master as 3.0",
    "sebastian/global-state": "dev-master as 6.0",
    "sebastian/recursion-context": "dev-master as 5.0",
    "sebastian/diff": "dev-master as 5.0",
    "sebastian/comparator": "dev-master as 5.0",
    "sebastian/exporter": "dev-master as 5.0",
    "phpunit/php-invoker": "dev-master as 4.0",
    "phpunit/php-timer": "dev-master as 6.0",
    "sebastian/cli-parser": "dev-master as 2.0",
    "sebastian/type": "dev-master as  3.0",
    "sebastian/environment": "dev-master as 3.0",
    "sebastian/code-unit-reverse-lookup": "dev-master as 3.0",
    "phpunit/php-text-template": "dev-master as 3.0",
    "phpunit/php-file-iterator": "dev-master as 4.0",
    "sebastian/version": "dev-master as 4.0",
    "sebastian/complexity": "dev-master as 3.0",
    "sebastian/code-unit": "dev-master as 2.0",
    "sebastian/lines-of-code": "dev-master as 2.0",
    "phpunit/php-code-coverage": "dev-master as 10.0",
    "phpunit/phpunit": "dev-master"
  },
  "autoload": {
    "psr-4": {
      "Project\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  }
}
```
Create simple class like below in directory src
```
<?php

namespace Project;

class Summator
{
    public function add(int $a, int $b)
    {
        return $a + $b;
    }
}
```
Create simple test like below in directory tests
```
<?php

namespace Tests;

use Project\Summator;
use PHPUnit\Framework\TestCase;

class SummatorTest extends TestCase
{
    public function testAdd()
    {
        $s = new Summator();
        self::assertEquals(2, $s->add(1,1));
    }
}
```
Click RMB on directory `tests` in PhpStorm and try to run all tests

#### Expected behavior

Test run via PhpStorm should be successful.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this on the CLI:

```
$ phpunit --bootstrap Summator.php SummatorTest.php 
PHPUnit 10.0-ga9446f352 by Sebastian Bergmann and contributors.

.                                                                   1 / 1 (100%)

Time: 00:00.043, Memory: 6.00 MB

OK (1 test, 1 assertion)
```
```
$ phpunit --bootstrap Summator.php SummatorTest.php --teamcity

##teamcity[testCount count='1' flowId='28126']

##teamcity[testSuiteStarted name='Tests\SummatorTest' locationHint='php_qn:///home/sb/SummatorTest.php::\Tests\SummatorTest' flowId='28126']

##teamcity[testStarted name='testAdd' locationHint='php_qn:///home/sb/SummatorTest.php::\Tests\SummatorTest::testAdd' flowId='28126']

##teamcity[testFinished name='testAdd' duration='3' flowId='28126']

##teamcity[testSuiteFinished name='Tests\SummatorTest' flowId='28126']
```
What is the complete command (including all arguments and options) that PhpStorm uses to invoke PHPUnit?

**Comment by isfedorov** [comment]
@sebastianbergmann the full command is like`/usr/bin/php /Project/vendor/phpunit/phpunit/phpunit --no-configuration /Project/tests --teamcity`. If remove `--teamcity` from the command then test run works but with `--teamcity` option it fails

**Comment by sebastianbergmann** [comment]
I still cannot reproduce this:

```
$ phpunit --no-configuration --bootstrap Summator.php SummatorTest.php --teamcity

##teamcity[testCount count='1' flowId='28398']

##teamcity[testSuiteStarted name='Tests\SummatorTest' locationHint='php_qn:///home/sb/SummatorTest.php::\Tests\SummatorTest' flowId='28398']

##teamcity[testStarted name='testAdd' locationHint='php_qn:///home/sb/SummatorTest.php::\Tests\SummatorTest::testAdd' flowId='28398']

##teamcity[testFinished name='testAdd' duration='2' flowId='28398']

##teamcity[testSuiteFinished name='Tests\SummatorTest' flowId='28398']
```

**Comment by isfedorov** [comment]
The reason is that you use --bootstrap. I've just performed command `/usr/local/Cellar/php/8.0.12/bin/php /Users/ivan.fedorov/PhpstormProjects/PhpUnit10Test/vendor/phpunit/phpunit/phpunit --bootstrap src/Summator.php tests/SummatorTest.php --teamcity` and everything worked fine. But with autoloading and composer it doesn't work.

**Comment by sebastianbergmann** [comment]
I fail to see how class loading would get in the way here, sorry.

**Comment by isfedorov** [comment]
I'm not sure how it affects the run neither but I see that using `--bootstrap` in the command makes the run successful, and removing this option produces error described above. Due to some reason `$testSuite` has type `TestSuiteWithName` when --bootstrap option isn't used and assertion fails

**Comment by sebastianbergmann** [comment]
Sure, I do not dispute that. This needs debugging, thank you for reporting this. I do not know when I will be able to look into this as I am busy with other work in PHPUnit's codebase at the moment.
