### ISSUE TITLE
Error with config file not found in AbstractPhpProcess.php

### ISSUE THREAD

**Issue by joachim-n** [sebastianbergmann/phpunit#4974]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.10
| PHP version         | 8.0.11
| Installation Method | Composer 

#### Summary

Inside a Docker shell, I did `vendor/bin/phpunit -c ./phpunit-docker.xml path/to/test/file` and got:

```
1) Drupal\Tests\wsd_api_mysql\Kernel\ProjectUpdateTest::testProjectCreationCommonsWorker
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught PHPUnit\Util\Xml\Exception: Could not read "./phpunit-docker.xml". in /var/www/vendor/phpunit/phpunit/src/Util/Xml/Loader.php:38
Stack trace:
#0 /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/Loader.php(71): PHPUnit\Util\Xml\Loader->loadFile('./phpunit-docke...', false, true, true)
#1 Standard input code(97): PHPUnit\TextUI\XmlConfiguration\Loader->load('./phpunit-docke...')
#2 {main}

Next PHPUnit\TextUI\XmlConfiguration\Exception: Could not read "./phpunit-docker.xml". in /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/Loader.php:73
Stack trace:
#0 Standard input code(97): PHPUnit\TextUI\XmlConfiguration\Loader->load('./phpunit-docke...')
#1 {main}
  thrown in /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/Loader.php on line 73
Fatal error: Uncaught PHPUnit\Util\Xml\Exception: Could not read "./phpunit-docker.xml". in /var/www/vendor/phpunit/phpunit/src/Util/Xml/Loader.php:38
Stack trace:
#0 /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/Loader.php(71): PHPUnit\Util\Xml\Loader->loadFile('./phpunit-docke...', false, true, true)
#1 Standard input code(97): PHPUnit\TextUI\XmlConfiguration\Loader->load('./phpunit-docke...')
#2 {main}

Next PHPUnit\TextUI\XmlConfiguration\Exception: Could not read "./phpunit-docker.xml". in /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/Loader.php:73
Stack trace:
#0 Standard input code(97): PHPUnit\TextUI\XmlConfiguration\Loader->load('./phpunit-docke...')
#1 {main}
  thrown in /var/www/vendor/phpunit/phpunit/src/TextUI/XmlConfiguration/Loader.php on line 73

/var/www/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:270
/var/www/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:187
/var/www/vendor/phpunit/phpunit/src/Framework/TestSuite.php:677
/var/www/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:673
/var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:143
/var/www/vendor/phpunit/phpunit/src/TextUI/Command.php:96
/var/www/vendor/bin/phpunit:120
```

Looking at https://stackoverflow.com/questions/32274862/phpunit-could-not-read-phpunit-xml-on-travis-ci gave me the idea to try the absolute path `vendor/bin/phpunit -c /var/www/phpunit-docker.xml path/to/test/file`. This worked correctly.

#### Expected behavior

Could the error message be improved? At least if the error said *where* PHPUnit was looking for the config file, it would immediately alert a developer that it's a relative path problem.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it.
