### ISSUE TITLE
PHP 8.2 feature `SensitiveParameter` test failed under condition

### ISSUE THREAD

**Issue by llaville** [sebastianbergmann/phpunit#5047]
Hello 

| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.24
| PHP version         | 8.2.0RC1
| Installation Method | PHAR (from https://phar.phpunit.de/phpunit-9.5.24.phar)

#### Summary

I wanted to test the new PHP 8.2 feature Sensitive Parameter value redaction support (as explained at https://php.watch/versions/8.2/backtrace-parameter-redaction)

When my test case in on global namespace, result is as expected. But when I put the test into a custom namespace, test failed.

Did I missed something, or is it a PHP core bug ?

#### Current behavior

Test failed when use case is under a custom namespace (like `Foo`)

```text
PHPUnit 9.5.24 #StandWithUkraine

Test 'Foo\Php82TestCase::testSensitiveParameter' started
Test 'Foo\Php82TestCase::testSensitiveParameter' ended


Time: 00:00, Memory: 22.37 MB

There was 1 failure:

1) Foo\Php82TestCase::testSensitiveParameter
Failed asserting that '#0 /shared/backups/bartlett/php-compatinfo-db/Php82TestCase.php(10): Foo\passwordHash('hunter2')\n
#1 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(1264): Foo\Php82TestCase->testSensitiveParameter()\n
#2 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(930): PHPUnit\Framework\TestCase->runTest()\n
#3 phar:///usr/local/bin/phpunit/phpunit/Framework/TestResult.php(586): PHPUnit\Framework\TestCase->runBare()\n
#4 phar:///usr/local/bin/phpunit/phpunit/Framework/TestCase.php(723): PHPUnit\Framework\TestResult->run(Object(Foo\Php82TestCase))\n
#5 phar:///usr/local/bin/phpunit/phpunit/Framework/TestSuite.php(504): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))\n
#6 phar:///usr/local/bin/phpunit/phpunit/TextUI/TestRunner.php(489): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))\n
#7 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(124): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)\n
#8 phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php(93): PHPUnit\TextUI\Command->run(Array, true)\n
#9 /usr/local/bin/phpunit(2299): PHPUnit\TextUI\Command::main()\n
' matches PCRE pattern "/SensitiveParameterValue/".

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

#### How to reproduce

Source code : **Filename** Php82TestCase.php
```php
<?php
namespace Foo;

class Php82TestCase extends \PHPUnit\Framework\TestCase
{
    public function testSensitiveParameter(): void
    {
        $this->expectOutputRegex('/SensitiveParameterValue/');

        passwordHash('hunter2');
    }

}

function passwordHash(#[SensitiveParameter] string $password): void
{
    \debug_print_backtrace();
}
```

Run command : `phpunit Php82TestCase.php --debug --do-not-cache-result --no-configuration`

#### Expected behavior

Test should produced same result as when use case is under global namespace

When I remove `namespace Foo` in my test script, I got these results

```text
PHPUnit 9.5.24 #StandWithUkraine

Test 'Php82TestCase::testSensitiveParameter' started
Test 'Php82TestCase::testSensitiveParameter' ended


Time: 00:00, Memory: 22.37 MB

OK (1 test, 1 assertion)
```

**Comment by sebastianbergmann** [comment]
You need to import `\SensitiveParameter`, I guess.

**Comment by llaville** [comment]
@sebastianbergmann Thanks for review. I'm wrong about namespace resolver process until I read again the PHP manual page (https://www.php.net/manual/en/language.namespaces.fallback.php).
