### ISSUE TITLE
Call to undefined method ReflectionMethod::getAttributes() when running phpunit with PHP 7.4

### ISSUE THREAD

**Issue by norgeindian** [sebastianbergmann/phpunit#5072]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.24
| PHP version         | 7.4.30
| Installation Method | Composer

#### Summary

Since we update to the PHPUnit version above, our pipeline fails.

#### Current behavior

We get the following error:
```
Unable to parse fixtures
Caused By: Call to undefined method ReflectionMethod::getAttributes()
#0 /opt/atlassian/pipelines/agent/build/dev/tests/integration/framework/Magento/TestFramework/Annotation/Parser/Composite.php(47): Magento\TestFramework\Fixture\Parser\IndexerDimensionMode->parse(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest), 'method')
#1 /opt/atlassian/pipelines/agent/build/dev/tests/integration/framework/Magento/TestFramework/Annotation/IndexerDimensionMode.php(165): Magento\TestFramework\Annotation\Parser\Composite->parse(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest), 'method')
#2 /opt/atlassian/pipelines/agent/build/dev/tests/integration/framework/Magento/TestFramework/Annotation/IndexerDimensionMode.php(105): Magento\TestFramework\Annotation\IndexerDimensionMode->parse(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest))
#3 [internal function]: Magento\TestFramework\Annotation\IndexerDimensionMode->startTest(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest))
#4 /opt/atlassian/pipelines/agent/build/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#5 /opt/atlassian/pipelines/agent/build/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(127): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#6 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/Framework/TestResult.php(438): Magento\TestFramework\Event\PhpUnit->startTest(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest))
#7 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/Framework/TestResult.php(661): PHPUnit\Framework\TestResult->startTest(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest))
#8 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/Framework/TestCase.php(903): PHPUnit\Framework\TestResult->run(Object(Vendor\Module\Test\Integration\Controller\JsInclusionTest))
#9 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#10 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/Framework/TestSuite.php(672): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(673): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#14 /opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#15 phpvfscomposer:///opt/atlassian/pipelines/agent/build/vendor/phpunit/phpunit/phpunit(97): PHPUnit\TextUI\Command::main()
#16 /opt/atlassian/pipelines/agent/build/vendor/bin/phpunit(118): include('phpvfscomposer:...')
#17 {main}

```

#### How to reproduce

Run phpunit in the mentioned versions.

#### Expected behavior

This should not throw an error. With PHP 8.1 the error is gone and everything works as expected.

**Comment by sebastianbergmann** [comment]
PHPUnit 9.5 does not call `ReflectionMethod::getAttributes()`.

**Comment by sebastianbergmann** [comment]
This does not happen in PHPUnit's code, but in Magento: https://github.com/extdn/github-actions-m2/issues/73

**Comment by norgeindian** [comment]
@sebastianbergmann , thanks a lot for pointing that out, and sorry to falsely bug you here.
