### ISSUE TITLE
StandardTestSuiteLoader regression in PHPUnit 9.5.28

### ISSUE THREAD

**Issue by enumag** [sebastianbergmann/phpunit#5139]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 9.5.28
| PHP version         | 8.2.1
| Installation Method | Composer

#### Summary

Earlier today I ran a full composer update and Paratest started failing. I reported the issue [here](https://github.com/paratestphp/paratest/issues/716) however after some more digging the bug isn't caused by Paratest but rather recent change in PHPUnit's StandardTestSuiteLoader. In particular this commit is causing the issue: https://github.com/sebastianbergmann/phpunit/commit/83eaffa12425bb512ba55f466ed9092dcb8e3ffe

#### Current behavior

Current implementation of PHPUnit's StandardTestSuiteLoader returns ReflectionClass for cases where it previously threw an exception. This change is causing Paratest to crash completely.

```
Fatal error: Uncaught TypeError: PHPUnit\Util\Annotation\DocBlock::__construct(): Argument #4 ($startLine) must be of type int, bool given, called in /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php on line 145 and defined in /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php:164
Stack trace:
#0 /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php(145): PHPUnit\Util\Annotation\DocBlock->__construct('', true, Array, false, false, false, '__construct', 'Exception')
#1 /app/vendor/phpunit/phpunit/src/Util/Annotation/Registry.php(93): PHPUnit\Util\Annotation\DocBlock::ofMethod(Object(ReflectionMethod), 'Exception')
#2 /app/vendor/phpunit/phpunit/src/Util/Test.php(590): PHPUnit\Util\Annotation\Registry->forMethod('Exception', '__construct')
#3 /app/vendor/brianium/paratest/src/Parser/Parser.php(118): PHPUnit\Util\Test::isTestMethod(Object(ReflectionMethod))
#4 /app/vendor/brianium/paratest/src/Parser/Parser.php(94): ParaTest\Parser\Parser->getMethods()
#5 /app/vendor/brianium/paratest/src/Runners/PHPUnit/SuiteLoader.php(192): ParaTest\Parser\Parser->getClass()
#6 /app/vendor/brianium/paratest/src/Runners/PHPUnit/SuiteLoader.php(171): ParaTest\Runners\PHPUnit\SuiteLoader->initSuites()
#7 /app/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(96): ParaTest\Runners\PHPUnit\SuiteLoader->load()
#8 /app/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(77): ParaTest\Runners\PHPUnit\BaseRunner->load(Object(ParaTest\Runners\PHPUnit\SuiteLoader))
#9 /app/vendor/brianium/paratest/src/Console/Commands/ParaTestCommand.php(101): ParaTest\Runners\PHPUnit\BaseRunner->run()
#10 /app/vendor/symfony/console/Command/Command.php(312): ParaTest\Console\Commands\ParaTestCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(ParaTest\Console\Commands\ParaTestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/brianium/paratest/bin/paratest(37): Symfony\Component\Console\Application->run()
#15 /app/vendor/bin/paratest(120): include('/app/vendor/bri...')
#16 {main}
  thrown in /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php on line 164
```

#### How to reproduce

Run Paratest with the latest PHPUnit 9.5.28.

#### Expected behavior

No failure.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by enumag** [comment]
Added a failing testcase in #5141.

**Comment by sebastianbergmann** [comment]
See https://github.com/sebastianbergmann/phpunit/pull/5141#issuecomment-1384952430.

**Comment by Slamdunk** [comment]
Fixed in https://github.com/paratestphp/paratest/pull/717
