### ISSUE TITLE
Undefined index, uncaught exception with --coverage-html argument

### ISSUE THREAD

**Issue by Tatsh** [sebastianbergmann/phpunit#517]
Installed with Gentoo:

```
[I] dev-php/phpunit
    Available versions:  3.5.13 (~)3.6.0
    Installed versions:  3.6.0(03:39:58 15/01/12)
    Homepage:            http://www.phpunit.de/
    Description:         Unit testing framework for PHP5

[I] dev-php/php-codecoverage
    Available versions:  (~)1.0.0 1.0.4 (~)1.1.0
    Installed versions:  1.1.0(03:39:46 15/01/12)
    Homepage:            http://pear.phpunit.de
    Description:         Library that provides collection, processing, and rendering functionality for PHP code coverage

$ phpunit --coverage-html ./report --stderr sHTMLTest.php
PHPUnit 3.6.0 by Sebastian Bergmann.

PHP Notice:  Undefined index: addUncoveredFilesFromWhitelist in /usr/share/php/PHPUnit/TextUI/TestRunner.php on line 254
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:126
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:188

Notice: Undefined index: addUncoveredFilesFromWhitelist in /usr/share/php/PHPUnit/TextUI/TestRunner.php on line 254

Call Stack:
    0.0001     635744   1. {main}() /usr/bin/phpunit:0
    0.0027    1148776   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
    0.0027    1149392   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:126
    0.0213    4089552   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:188

PHP Fatal error:  Uncaught exception 'InvalidArgumentException' in /usr/share/php/PHP/CodeCoverage.php:386
Stack trace:
#0 /usr/share/php/PHPUnit/TextUI/TestRunner.php(255): PHP_CodeCoverage->setProcessUncoveredFilesFromWhitelist(NULL)
#1 /usr/share/php/PHPUnit/TextUI/Command.php(188): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 /usr/share/php/PHPUnit/TextUI/Command.php(126): PHPUnit_TextUI_Command->run(Array, true)
#3 /usr/bin/phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in /usr/share/php/PHP/CodeCoverage.php on line 386

Fatal error: Uncaught exception 'InvalidArgumentException' in /usr/share/php/PHP/CodeCoverage.php on line 386

InvalidArgumentException:  in /usr/share/php/PHP/CodeCoverage.php on line 386

Call Stack:
    0.0001     635744   1. {main}() /usr/bin/phpunit:0
    0.0027    1148776   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
    0.0027    1149392   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:126
    0.0213    4089552   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:188
    0.0234    4508488   5. PHP_CodeCoverage->setProcessUncoveredFilesFromWhitelist() /usr/share/php/PHPUnit/TextUI/TestRunner.php:255
```

The file in question: https://github.com/tatsh/sutra/blob/master/tests/sHTMLTest.php

**Comment by staabm** [comment]
@sebastianbergmann got the same notice when running phpunit with coverage on composer at  24168d9d5c0ab0103cd6d17a86dea99c11196cd3

```
Notice: Undefined index: processUncoveredFilesFromWhitelist in C:\Users\staabm\Documents\GitHub\composer\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 862

Call Stack:
    0.0020     221024   1. {main}() C:\Users\staabm\AppData\Local\Temp\ide-phpunit.php:0
    0.0119     593384   2. IDE_Base_PHPUnit_TextUI_Command::main() C:\Users\staabm\AppData\Local\Temp\ide-phpunit.php:552
    0.0119     599680   3. PHPUnit_TextUI_Command->run() C:\Users\staabm\AppData\Local\Temp\ide-phpunit.php:294
    1.3544   15694632   4. PHPUnit_TextUI_TestRunner->doRun() C:\xampp1.8.0\php\pear\PHPUnit\TextUI\Command.php:192
    1.3544   15696168   5. PHPUnit_TextUI_TestRunner->handleConfiguration() C:\Users\staabm\Documents\GitHub\composer\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:149

PHPUnit 3.6.12 by Sebastian Bergmann.
```

**Comment by sebastianbergmann** [comment]
Sorry, but PHPUnit 3.6 is not no longer supported. Please open a new issue if the problem persists with PHPUnit 4.7.

**Comment by staabm** [comment]
ohh didn't realized that phpstorm picked up a phpunit version lingering around somewhere in the %PATH% from the old days. thanks for hint.
