### ISSUE TITLE
JUnit logger crashes when test is skipped by missing PHP extension when running in separate process

### ISSUE THREAD

**Issue by MauricioFauth** [sebastianbergmann/phpunit#5258]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.12
| PHP version         | 8.1.14
| Installation Method | Composer

#### Summary

The JUnit logger crashes when a test is skipped because of missing required PHP extension when running in separate process.

#### Current behavior

```
PHPUnit 10.0.12 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.14
Configuration: /path/phpunit-10-test/phpunit.xml

.S                                                                  2 / 2 (100%)

An error occurred inside PHPUnit.

Message:  assert($this->currentTestCase !== null)
Location: /path/phpunit-10-test/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 /path/phpunit-10-test/vendor/phpunit/phpunit/src/TextUI/Application.php(142): PHPUnit\TextUI\TestRunner->run()
#1 /path/phpunit-10-test/vendor/phpunit/phpunit/phpunit(90): PHPUnit\TextUI\Application->run()
#2 /path/phpunit-10-test/vendor/bin/phpunit(123): include('...')
#3 {main}
```

#### How to reproduce

`phpunit.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.0/phpunit.xsd"
         bootstrap="vendor/autoload.php">
    <testsuites>
        <testsuite name="default">
            <directory>tests</directory>
        </testsuite>
    </testsuites>

    <logging>
        <junit outputFile="junit.xml"/>
    </logging>
</phpunit>
```

`tests/FooTest.php`
```php
<?php

declare(strict_types=1);

use PHPUnit\Framework\Attributes\RequiresPhpExtension;
use PHPUnit\Framework\Attributes\RunInSeparateProcess;
use PHPUnit\Framework\TestCase;

class FooTest extends TestCase
{
    public function testOne(): void
    {
        $this->assertTrue(true);
    }

    #[RunInSeparateProcess]
    #[RequiresPhpExtension('notinstalled')]
    public function testTwo(): void
    {
        $this->assertTrue(true);
    }
}
```

#### Expected behavior

```
PHPUnit 10.0.11 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.14
Configuration: /path/phpunit-10-test/phpunit.xml

.S                                                                  2 / 2 (100%)

Time: 00:00.067, Memory: 8.00 MB

OK, but some tests were skipped!
Tests: 2, Assertions: 1, Skipped: 1.
```

**Comment by sebastianbergmann** [comment]
@Slamdunk Can you have a look at this, please? Thanks!

**Comment by sebastianbergmann** [comment]
I added a test case in def6b4f425438a339accd2b905344383c7c2bb7f.

**Comment by sebastianbergmann** [comment]
After e1e8aab55f9d32c9a2ac98bfed544ff0b5de4e0b the full crash message is now:
```
An error occurred inside PHPUnit.

Message:  assert($this->currentTestCase !== null)
Location: /usr/local/src/phpunit/src/TextUI/TestRunner.php:68

#0 /usr/local/src/phpunit/src/TextUI/Application.php(141): PHPUnit\TextUI\TestRunner->run()
#1 /usr/local/src/phpunit/phpunit(90): PHPUnit\TextUI\Application->run()
#2 {main}

Caused by: /usr/local/src/phpunit/src/Logging/JUnit/JunitXmlLogger.php:338

#0 /usr/local/src/phpunit/src/Logging/JUnit/JunitXmlLogger.php(338): assert()
#1 /usr/local/src/phpunit/src/Logging/JUnit/JunitXmlLogger.php(208): PHPUnit\Logging\JUnit\JunitXmlLogger->handleIncompleteOrSkipped()
#2 /usr/local/src/phpunit/src/Logging/JUnit/Subscriber/TestSkippedSubscriber.php(28): PHPUnit\Logging\JUnit\JunitXmlLogger->testSkipped()
#3 /usr/local/src/phpunit/src/Event/Dispatcher/DirectDispatcher.php(99): PHPUnit\Logging\JUnit\TestSkippedSubscriber->notify()
#4 /usr/local/src/phpunit/src/Event/Dispatcher/DeferringDispatcher.php(45): PHPUnit\Event\DirectDispatcher->dispatch()
#5 /usr/local/src/phpunit/src/Event/Facade.php(97): PHPUnit\Event\DeferringDispatcher->dispatch()
#6 /usr/local/src/phpunit/src/Util/PHP/AbstractPhpProcess.php(313): PHPUnit\Event\Facade::forward()
#7 /usr/local/src/phpunit/src/Util/PHP/AbstractPhpProcess.php(166): PHPUnit\Util\PHP\AbstractPhpProcess->processChildResult()
#8 /usr/local/src/phpunit/src/Framework/TestRunner.php(343): PHPUnit\Util\PHP\AbstractPhpProcess->runTestJob()
#9 /usr/local/src/phpunit/src/Framework/TestCase.php(458): PHPUnit\Framework\TestRunner->runInSeparateProcess()
#10 /usr/local/src/phpunit/src/Framework/TestSuite.php(352): PHPUnit\Framework\TestCase->run()
#11 /usr/local/src/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()
#12 /usr/local/src/phpunit/src/TextUI/Application.php(141): PHPUnit\TextUI\TestRunner->run()
#13 /usr/local/src/phpunit/phpunit(90): PHPUnit\TextUI\Application->run()
#14 {main}
```
