### ISSUE TITLE
problem in "--xml" key

### ISSUE THREAD

**Issue by Krakozaber** [sebastianbergmann/phpunit#5280]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.0.16
| PHP version         | 8.2
| Installation Method | Composer

problem in "--xml" key

codecept run unit --xml --coverage-cobertura

```
Error: Call to undefined method unit\bankAccount\BankAccountServiceTest::hasOutput() in /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Reporter/JUnitReporter.php:250
Stack trace:
#0 /mnt/data/www/pirs/vendor/symfony/event-dispatcher/EventDispatcher.php(206): Codeception\Reporter\JUnitReporter->endTest()
#1 /mnt/data/www/pirs/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#2 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Test/Test.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#3 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Suite.php(130): Codeception\Test\Test->realRun()
#4 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/SuiteManager.php(148): Codeception\Suite->run()
#5 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Codecept.php(260): Codeception\SuiteManager->run()
#6 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept->runSuite()
#7 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Command/Run.php(646): Codeception\Codecept->run()
#8 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Command/Run.php(467): Codeception\Command\Run->runSuites()
#9 /mnt/data/www/pirs/vendor/symfony/console/Command/Command.php(312): Codeception\Command\Run->execute()
#10 /mnt/data/www/pirs/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run()
#11 /mnt/data/www/pirs/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
#12 /mnt/data/www/pirs/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
#13 /mnt/data/www/pirs/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application->run()
#14 /mnt/data/www/pirs/vendor/codeception/codeception/app.php(45): Codeception\Application->run()
#15 /mnt/data/www/pirs/vendor/codeception/codeception/app.php(46): {closure}()
#16 /mnt/data/www/pirs/vendor/codeception/codeception/codecept(7): require('...')
#17 /mnt/data/www/pirs/vendor/bin/codecept(120): include('...')
#18 {main}
```

**Comment by sebastianbergmann** [comment]
Please report issues related to Codeception in their issue tracker.
