### ISSUE TITLE
Cannot find TestCase object on call stack

### ISSUE THREAD

**Issue by arturasfrontit** [sebastianbergmann/phpunit#5339]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.1.1
| PHP version         | 8.1.18
| Installation Method | Composer 

#### Summary

```bash
dockeruser@8de76b63ec0c:~$ php artisan test

   PASS  Tests\Unit\ExampleTest
  ✓ that true is true


An error occurred inside PHPUnit.

Message:  Cannot find TestCase object on call stack
Location: /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(165): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#1 /var/www/html/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run(Array)
#2 {main}

Caused by: /var/www/html/vendor/phpunit/phpunit/src/Runner/ErrorHandler.php:168

#0 /var/www/html/vendor/phpunit/phpunit/src/Runner/ErrorHandler.php(74): PHPUnit\Runner\ErrorHandler->testValueObjectForEvents()
#1 [internal function]: PHPUnit\Runner\ErrorHandler->__invoke(2, 'file_put_conten...', '/var/www/html/v...', 143)
#2 /var/www/html/vendor/phpunit/phpunit/src/Runner/ResultCache/DefaultResultCache.php(143): file_put_contents('/var/www/html/....', '{"version":1,"d...', 2)
#3 /var/www/html/vendor/phpunit/phpunit/src/Runner/ResultCache/ResultCacheHandler.php(58): PHPUnit\Runner\ResultCache\DefaultResultCache->persist()
#4 /var/www/html/vendor/phpunit/phpunit/src/Runner/ResultCache/Subscriber/TestSuiteFinishedSubscriber.php(22): PHPUnit\Runner\ResultCache\ResultCacheHandler->testSuiteFinished()
#5 /var/www/html/vendor/phpunit/phpunit/src/Event/Dispatcher/DirectDispatcher.php(115): PHPUnit\Runner\ResultCache\TestSuiteFinishedSubscriber->notify(Object(PHPUnit\Event\TestSuite\Finished))
#6 /var/www/html/vendor/phpunit/phpunit/src/Event/Dispatcher/DeferringDispatcher.php(53): PHPUnit\Event\DirectDispatcher->dispatch(Object(PHPUnit\Event\TestSuite\Finished))
#7 /var/www/html/vendor/phpunit/phpunit/src/Event/Emitter/DispatchingEmitter.php(986): PHPUnit\Event\DeferringDispatcher->dispatch(Object(PHPUnit\Event\TestSuite\Finished))
#8 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(362): PHPUnit\Event\DispatchingEmitter->testSuiteFinished(Object(PHPUnit\Event\TestSuite\TestSuiteWithName))
#9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()
#10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(165): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#11 /var/www/html/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run(Array)
#12 {main}
dockeruser@8de76b63ec0c:~$ 
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="./vendor/phpunit/phpunit/phpunit.xsd"
         bootstrap="vendor/autoload.php"
         colors="true"
>
    <testsuites>
        <testsuite name="Unit">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
        <testsuite name="Feature">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>
    </testsuites>
    <source>
        <include>
            <directory suffix=".php">./app</directory>
        </include>
    </source>
    <php>
        <env name="APP_ENV" value="testing"/>
        <env name="BCRYPT_ROUNDS" value="4"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="DB_DATABASE" value="testing"/>
        <env name="MAIL_MAILER" value="array"/>
        <env name="QUEUE_CONNECTION" value="sync"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="TELESCOPE_ENABLED" value="false"/>
    </php>
</phpunit>

```

`./vendor/bin/phpunit`

```bash
dockeruser@8de76b63ec0c:~$ ./vendor/bin/phpunit  
PHPUnit 10.1.1 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.18
Configuration: /var/www/html/phpunit.xml

..                                                                  2 / 2 (100%)

An error occurred inside PHPUnit.

Message:  Cannot find TestCase object on call stack
Location: /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:68

#0 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(165): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#1 /var/www/html/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run(Array)
#2 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#3 {main}

Caused by: /var/www/html/vendor/phpunit/phpunit/src/Runner/ErrorHandler.php:168

#0 /var/www/html/vendor/phpunit/phpunit/src/Runner/ErrorHandler.php(74): PHPUnit\Runner\ErrorHandler->testValueObjectForEvents()
#1 [internal function]: PHPUnit\Runner\ErrorHandler->__invoke(2, 'file_put_conten...', '/var/www/html/v...', 143)
#2 /var/www/html/vendor/phpunit/phpunit/src/Runner/ResultCache/DefaultResultCache.php(143): file_put_contents('/var/www/html/....', '{"version":1,"d...', 2)
#3 /var/www/html/vendor/phpunit/phpunit/src/Runner/ResultCache/ResultCacheHandler.php(58): PHPUnit\Runner\ResultCache\DefaultResultCache->persist()
#4 /var/www/html/vendor/phpunit/phpunit/src/Runner/ResultCache/Subscriber/TestSuiteFinishedSubscriber.php(22): PHPUnit\Runner\ResultCache\ResultCacheHandler->testSuiteFinished()
#5 /var/www/html/vendor/phpunit/phpunit/src/Event/Dispatcher/DirectDispatcher.php(115): PHPUnit\Runner\ResultCache\TestSuiteFinishedSubscriber->notify(Object(PHPUnit\Event\TestSuite\Finished))
#6 /var/www/html/vendor/phpunit/phpunit/src/Event/Dispatcher/DeferringDispatcher.php(53): PHPUnit\Event\DirectDispatcher->dispatch(Object(PHPUnit\Event\TestSuite\Finished))
#7 /var/www/html/vendor/phpunit/phpunit/src/Event/Emitter/DispatchingEmitter.php(986): PHPUnit\Event\DeferringDispatcher->dispatch(Object(PHPUnit\Event\TestSuite\Finished))
#8 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(362): PHPUnit\Event\DispatchingEmitter->testSuiteFinished(Object(PHPUnit\Event\TestSuite\TestSuiteWithName))
#9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(63): PHPUnit\Framework\TestSuite->run()
#10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Application.php(165): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\TextUI\Configuration\Configuration), Object(PHPUnit\Runner\ResultCache\DefaultResultCache), Object(PHPUnit\Framework\TestSuite))
#11 /var/www/html/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run(Array)
#12 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#13 {main}
dockeruser@8de76b63ec0c:~$ 
```

`tests/Feature/ExampleTest.php`

```php
<?php

namespace Tests\Feature;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     */
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
```

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by arturasfrontit** [comment]
> Thank you for your report.
> 
> Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.
> 
> Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

```php
<?php

namespace Tests\Feature;

// use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
    /**
     * A basic test example.
     */
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }
}
```

**Comment by sebastianbergmann** [comment]
This is not self-contained (as it uses the `Tests\TestCase` class from Laravel).

**Comment by code-distortion** [comment]
Hi @arturasfrontit. I found a situation that causes this exception to be thrown - Issue #5403

It looks like you're using Laravel as well,  so it might have been triggered for the same reason.

**Comment by arturasfrontit** [comment]
> Hi @arturasfrontit. I found a situation that causes this exception to be thrown - Issue #5403
> 
> It looks like you're using Laravel as well, so it might have been triggered for the same reason.

thank you
