### ISSUE TITLE
$name must not be accessed before initialization - appeared suddenly

### ISSUE THREAD

**Issue by anytizer** [sebastianbergmann/phpunit#5370]
https://github.com/sebastianbergmann/phpunit/blob/8fd4ab6e2194e191e2b96cb8e1dc94ec25f2971d/src/TextUI/TestRunner.php#L67-L70

Message:  Typed property PHPUnit\Framework\TestCase::$name must not be accessed before initialization
Location: phpunit\phpunit\src\TextUI\TestRunner.php:68

Tested in .phar and composer versions of phpunit.
PHP Version: > 8.2.1

**Comment by anytizer** [comment]
May be this article is useful.
https://madewithlove.com/blog/typed-property-must-not-be-accessed-before-initialization/

**Comment by anytizer** [comment]
Here is a minimal attachment.

Please extract the attachment in a new folder.
Put phpunit-10.1.3.phar file inside it (I am not attaching this here).
Run: issue-5370.bat

[tests-apis-phpunit.zip](https://github.com/sebastianbergmann/phpunit/files/11567819/tests-apis-phpunit.zip)

Trimmed error message is:
```
-\tests-apis-phpunit>php phpunit-10.1.3.phar --colors --testdox .
PHPUnit 10.1.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.1
Configuration: -\tests-apis-phpunit\phpunit.xml


An error occurred inside PHPUnit.

Message:  Typed property PHPUnit\Framework\TestCase::$name must not be accessed before initialization
Location: phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/TextUI/TestRunner.php:48

#0 phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/TextUI/Application.php(129): PHPUnit\TextUI\TestRunner->run()
#1 -\tests-apis-phpunit\phpunit-10.1.3.phar(2896): PHPUnit\TextUI\Application->run()
#2 {main}

Caused by: phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/Framework/TestCase.php:801

#0 phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/Runner/TestSuiteSorter.php(254): PHPUnit\Framework\TestCase->sortId()
#1 phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/Runner/TestSuiteSorter.php(256): PHPUnit\Runner\TestSuiteSorter->calculateTestExecutionOrder()
#2 phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/Runner/TestSuiteSorter.php(91): PHPUnit\Runner\TestSuiteSorter->calculateTestExecutionOrder()
#3 phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/TextUI/TestRunner.php(39): PHPUnit\Runner\TestSuiteSorter->reorderTestsInSuite()
#4 phar:-/tests-apis-phpunit/phpunit-10.1.3.phar/phpunit/TextUI/Application.php(129): PHPUnit\TextUI\TestRunner->run()
#5 -\tests-apis-phpunit\phpunit-10.1.3.phar(2896): PHPUnit\TextUI\Application->run()
#6 {main}
```

**Comment by sebastianbergmann** [comment]
You must not overwrite the constructor of `PHPUnit\Framework\TestCase` (without accepting all original arguments and passing them on).
