### ISSUE TITLE
Very basic test case with phpunit 10, docker and composer broken (works with 9) -> Class "PHPUnit\Metadata\Api\DataProvider" not found

### ISSUE THREAD

**Issue by Seikilos** [sebastianbergmann/phpunit#5411]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.2.2
| PHP version         | 8.2.7
| Installation Method | Composer

#### Summary

Starting a very basic phpunit test with composer runs into  `Message:  Class "PHPUnit\Metadata\Api\DataProvider" not found` in phpunit 10 and works with phpunit 9

#### Current behavior

```
An error occurred inside PHPUnit.

Message:  Class "PHPUnit\Metadata\Api\DataProvider" not found
Location: /app/vendor/phpunit/phpunit/src/Framework/TestBuilder.php:38

#0 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(477): PHPUnit\Framework\TestBuilder->build(Object(ReflectionClass), 'testCanBeCreate...')
#1 /app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(125): PHPUnit\Framework\TestSuite->addTestMethod(Object(ReflectionClass), Object(ReflectionMethod))
#2 /app/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(103): PHPUnit\Framework\TestSuite::fromClassReflector(Object(ReflectionClass))
#3 /app/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(47): PHPUnit\TextUI\Configuration\TestSuiteBuilder->testSuiteFromPath('/app/EmailTest....', Array)
#4 /app/vendor/phpunit/phpunit/src/TextUI/Application.php(348): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build(Object(PHPUnit\TextUI\Configuration\Configuration))
#5 /app/vendor/phpunit/phpunit/src/TextUI/Application.php(102): PHPUnit\TextUI\Application->buildTestSuite(Object(PHPUnit\TextUI\Configuration\Configuration))
#6 /app/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run(Array)
#7 /app/vendor/bin/phpunit(122): include('/app/vendor/php...')
#8 {main}
```

#### How to reproduce

On windows execute the attached powershell script or see manual steps below the powershell example.

Repro with powershell 
====
```ps1
Set-StrictMode -Version 3

$outDir = "$PSScriptRoot/out_dir"

if(Test-Path $outDir)
{
    Remove-Item -Force -Recurse $outDir | Out-Null
}

New-Item -ItemType Directory $outDir | Out-Null

@'
{
    "name": "root/app",
    "require-dev": {
        "phpunit/phpunit": "^10"
    }
}
'@ | Out-File $outDir\composer.json -Encoding ascii

docker run --volume "$($outDir):/app" --rm -it composer/composer composer update

@'
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class EmailTest extends TestCase
{
    public function testCanBeCreatedFromValidEmail(): void
    {
        $this->assertSame("foo", "foo");
    }   
}
'@ | Out-File $outDir\EmailTest.php -Encoding ascii

docker run --volume "$($outDir):/app" --rm -it composer/composer ./vendor/bin/phpunit EmailTest.php

```

Manual repro
===========

Create a `composer.json` file
```json
{
    "name": "root/app",
    "require-dev": {
        "phpunit/phpunit": "^10"
    }
}
```

Create a php test file `EmailTest.php`
```php
<?php declare(strict_types=1);
use PHPUnit\Framework\TestCase;

final class EmailTest extends TestCase
{
    public function testCanBeCreatedFromValidEmail(): void
    {
        $this->assertSame("foo", "foo");
    }   
}
```

Use docker to update
`docker run --volume "THE_DIR_OF_COMPOSER_FILE:/app" --rm -it composer/composer composer update`

Execute test
`docker run --volume "THE_DIR_OF_COMPOSER_FILE:/app" --rm -it composer/composer ./vendor/bin/phpunit EmailTest.php`

When I change `^10` to `^9` and run composer, the unit test passes.

#### Expected behavior

Test should pass without an error

**Comment by sebastianbergmann** [comment]
I cannot reproduce with just the `composer.json` and `EmailTest.php` files you provided. I am not using Docker and/or the container image you use. My assumption is that the container image contains an installation of PHPUnit that conflicts with the one you are installing.
