### ISSUE TITLE
Migrating configuration works, but with error output

### ISSUE THREAD

**Issue by arogachev** [sebastianbergmann/phpunit#5613]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.2
| PHP version         | 8.2.12
| Installation Method | Composer / PHAR

#### Summary

There is error output after migrating configuration, though it's successful. Further regular `vendor/bin/phpunit` calls with new config work as well

#### Current behavior

```shell
vendor/bin/phpunit --migrate-configuration
PHPUnit 10.5.2 by Sebastian Bergmann and contributors.

Created backup:         /extra/code/arogachev/rbac/phpunit.xml.dist.bak
Migrated configuration: /extra/code/arogachev/rbac/phpunit.xml.dist


An error occurred inside PHPUnit.

Message:  PHPUnit\TextUI\Application::execute(): never-returning function must not implicitly return
Location: /extra/code/arogachev/rbac/vendor/phpunit/phpunit/src/TextUI/Application.php:269

#0 /extra/code/arogachev/rbac/vendor/phpunit/phpunit/src/TextUI/Application.php(385): PHPUnit\TextUI\Application->execute()
#1 /extra/code/arogachev/rbac/vendor/phpunit/phpunit/src/TextUI/Application.php(91): PHPUnit\TextUI\Application->executeCommandsThatOnlyRequireCliConfiguration()
#2 /extra/code/arogachev/rbac/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#3 /extra/code/arogachev/rbac/vendor/bin/phpunit(123): include('...')
#4 {main}
PHP Fatal error:  Uncaught TypeError: PHPUnit\TextUI\Application::exitWithCrashMessage(): never-returning function must not implicitly return in /extra/code/arogachev/rbac/vendor/phpunit/phpunit/src/TextUI/Application.php:662
Stack trace:
#0 /extra/code/arogachev/rbac/vendor/phpunit/phpunit/src/TextUI/Application.php(255): PHPUnit\TextUI\Application->exitWithCrashMessage()
#1 /extra/code/arogachev/rbac/vendor/phpunit/phpunit/phpunit(99): PHPUnit\TextUI\Application->run()
#2 /extra/code/arogachev/rbac/vendor/bin/phpunit(123): include('...')
#3 {main}
  thrown in /extra/code/arogachev/rbac/vendor/phpunit/phpunit/src/TextUI/Application.php on line 662
```

#### How to reproduce

Old config (`phpunit.xml.dist`):

```xml
<?xml version="1.0" encoding="UTF-8"?>

<phpunit
    bootstrap="vendor/autoload.php"
    colors="true"
    verbose="true"
    failOnRisky="true"
    failOnWarning="true"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    stopOnFailure="false"
    executionOrder="random"
    resolveDependencies="true"
>
    <php>
        <ini name="error_reporting" value="-1"/>
    </php>

    <testsuites>
        <testsuite name="Yii Role-Based Access Control tests">
            <directory>./tests</directory>
        </testsuite>
    </testsuites>

    <coverage>
        <include>
            <directory>./src</directory>
        </include>
    </coverage>
</phpunit>
```

```shell
vendor/bin/phpunit --migrate-configuration
```

#### Expected behavior

No error output.

**Comment by sebastianbergmann** [comment]
I cannot reproduce this: with the XML configuration file you provided, the migration "just works" and I do not see an error.

**Comment by arogachev** [comment]
Thanks. Seems like it happens with other calls where arguments are provided, for example:

```shell
vendor/bin/phpunit --version
```

**Update:** the problem was with one of PHP extensions (https://github.com/krakjoe/uopz/issues/172) and irrelevant to PHPUnit. Closing, sorry.
