### ISSUE TITLE
Fatal error: Non-readonly class Success cannot extend readonly class Known in Success.php on line 17

### ISSUE THREAD

**Issue by scorpion3dd** [sebastianbergmann/phpunit#5736]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 11.0.5
| PHP version         | 8.2.7
| Installation Method | Composer 
| Symfony | 7.0.4

#### Summary

Fatal error: Non-readonly class PHPUnit\Framework\TestStatus\Success cannot extend reado
nly class PHPUnit\Framework\TestStatus\Known in /var/www/back/vendor/phpunit/phpunit/src
/Framework/TestStatus/Success.php on line 17

#### Current behavior

**Installed:**

- PHP 8.2.7
- Symfony 7.0.4
- phpunit/phpunit 11.0.5
- Installation Method - Composer

**Run:**
`php bin/phpunit --testsuite=Unit --no-coverage --configuration=/var/www/back/phpunit.xml --colors=always`

**Result:**
```
PHPUnit 11.0.5 by Sebastian Bergmann and contributors.
Runtime: PHP 8.2.7
Configuration: /var/www/back/phpunit.xml

Fatal error: Non-readonly class PHPUnit\Framework\TestStatus\Success cannot extend reado
nly class PHPUnit\Framework\TestStatus\Known in /var/www/back/vendor/phpunit/phpunit/src
/Framework/TestStatus/Success.php on line 17
```

**Tracing:**
in PHPUnit Framework in class TestStatus:
```
public static function success(): self
{
return new Success;
}
```
when this is executed (new Success;), an error is generated (Non-readonly class ...)
Class Hierarchy
```
final readonly class Success extends Known
abstract readonly class Known extends TestStatus
abstract readonly class TestStatus
```

**Request:**
Please help me figure out this problem, because all the tests in the project stopped working (all tests show this error) after updating PHPUnit to the version 11.0.5.

#### How to reproduce

Installed:

PHP 8.2.7
Symfony 7.0.4
phpunit/phpunit 11.0.5
Write any test, for example similar to this:
class ValidatorCommentUploadTest extends KernelTestCase

Run:
php bin/phpunit --testsuite=Unit --no-coverage --configuration=/var/www/back/phpunit.xml --colors=always

#### Expected behavior

All tests should have been executed and a report should have been displayed without errors.

**Comment by scorpion3dd** [comment]
In project by Symfony 7 Framework installed PHPUnit 11.0.5 Framework.
All installed by Composer.

Fragment composer show -i
```
symfony/phpunit-bridge                v7.0.4             Provides utilities for PHP
phpunit/php-code-coverage             11.0.2             Library that provides coll...  
phpunit/php-file-iterator             5.0.0              FilterIterator implementat...  
phpunit/php-invoker                   5.0.0              Invoke callables with a ti...  
phpunit/php-text-template             4.0.0              Simple template engine.        
phpunit/php-timer                     7.0.0              Utility class for timing       
phpunit/phpunit                       11.0.5             The PHP Unit Testing frame.
```

For example, there is such a validator class:
```
class ValidatorCommentUpload
{
    use LoggerTrait;

    /**
     * @param LoggerInterface $logger
     */
    public function __construct(
        LoggerInterface $logger
    ) {
        $this->logger = $logger;
        $this->debugConstruct(self::class);
    }

    /**
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @psalm-suppress InternalMethod
     * @param Request $request
     *
     * @return CommentDTO
     */
    public function validate(Request $request): CommentDTO
    {
        $message = 'Is required: ';
        /** @var UploadedFile|null $uploadedFile */
        $uploadedFile = $request->files->get('photoFile');
        if (empty($uploadedFile)) {
            $message .= '"photoFile", ';
        }
        $author = $request->get('author', '');
        if (! $author) {
            $message .= '"author", ';
        }
        $text = $request->get('text', '');
        if (! $text) {
            $message .= '"text", ';
        }
        $email = $request->get('email', '');
        if (! $email) {
            $message .= '"email", ';
        }
        $userIri = $request->get('user', '');
        if (! $userIri) {
            $message .= '"user IRI", ';
        }
        $userAr = explode('/', $userIri);
        $userId = isset($userAr[3]) && is_numeric($userAr[3]) ? (int)$userAr[3] : 0;
        if (! $userId) {
            $message .= '"user userId", ';
        }
        if ($message != 'Is required: ') {
            throw new BadRequestHttpException($message);
        }
        /** @var UploadedFile $uploadedFile */
        return new CommentDTO($userId, $author, $email, $text, $uploadedFile);
    }
}
```

For example, there is a unit test to check that validator class:
```
class ValidatorCommentUploadTest extends BaseKernelTestCase
{
    public const FULL_FILE_NAME = '/../data/Service/CommentService/london1.jpg';

    /** @var LoggerInterface $loggerMock */
    private LoggerInterface $loggerMock;

    /** @var ValidatorCommentUpload $validator */
    private ValidatorCommentUpload $validator;

    /**
     * @return void
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     */
    public function setUp(): void
    {
        parent::setUp();
        $this->loggerMock = $this->createMock(LoggerInterface::class);
        $this->validator = new ValidatorCommentUpload($this->loggerMock);
    }

    /**
     * @testCase - method validate - must be a success
     *
     * @dataProvider provideApiCommentUpload
     *
     * @param string $version
     * @param string $fileName
     * @param array $parameters
     *
     * @return void
     */
    public function testValidate(string $version, string $fileName, array $parameters): void
    {
        $photoFile = $this->getPostCommentUploadedFile(__DIR__ . $fileName);
        if (isset($photoFile)) {
            $files = ['photoFile' => $photoFile];
            $request = new Request([], $parameters, [], [], $files);
        } else {
            $request = new Request([], $parameters);
        }
        if ($version == '1') {
            $response = $this->validator->validate($request);
            $this->assertInstanceOf(CommentDTO::class, $response);
            $this->assertEquals($parameters['userId'], $response->userId);
            $this->assertEquals($parameters['author'], $response->author);
            $this->assertEquals($parameters['email'], $response->email);
            $this->assertEquals($parameters['text'], $response->text);
            $this->assertInstanceOf(UploadedFile::class, $response->uploadedFile);
        } else {
            $this->expectException(BadRequestHttpException::class);
            $this->expectExceptionMessage('Is required: ');
            $this->validator->validate($request);
        }
    }

    /**
     * @return iterable
     */
    public static function provideApiCommentUpload(): iterable
    {
        $version = '1';
        $fileName = self::FULL_FILE_NAME;
        $parameters = [
            'author' => 'Aroner Jacobson',
            'text' => "It's a great idea, from API POST",
            'email' => 'leta7864381@runolfsdottir.com',
            'user' => '/api/users/8',
            'userId' => 8
        ];
        yield $version => [$version, $fileName, $parameters];

        $version = '2';
        $parameters = [
            'author' => '',
            'text' => "It's a great idea, from API POST",
            'email' => 'leta786438@runolfsdottir.com',
            'user' => '/api/users/8',
            'userId' => 8
        ];
        yield $version => [$version, $fileName, $parameters];

        $version = '3';
        $parameters = [
            'author' => 'Aroner Jacobson',
            'text' => "",
            'email' => 'leta786438@runolfsdottir.com',
            'user' => '/api/users/8',
            'userId' => 8
        ];
        yield $version => [$version, $fileName, $parameters];

        $version = '4';
        $parameters = [
            'author' => 'Aroner Jacobson',
            'text' => "It's a great idea, from API POST",
            'email' => '',
            'user' => '/api/users/8',
            'userId' => 8
        ];
        yield $version => [$version, $fileName, $parameters];

        $version = '5';
        $parameters = [
            'author' => 'Aroner Jacobson',
            'text' => "It's a great idea, from API POST",
            'email' => 'leta786438@runolfsdottir.com',
            'user' => '',
            'userId' => 0
        ];
        yield $version => [$version, $fileName, $parameters];

        $version = '6';
        $fileName = 'qwerty.jpg';
        $parameters = [
            'author' => 'Aroner Jacobson',
            'text' => "It's a great idea, from API POST",
            'email' => 'leta786438@runolfsdottir.com',
            'user' => '/api/users/8',
            'userId' => 8
        ];
        yield $version => [$version, $fileName, $parameters];
    }
}
```

There are entries in the file composer.jso in the section "scripts":
```
"check-phpunit-vendor-version": "php vendor/phpunit/phpunit/phpunit --version --colors=always",
"check-phpunit-filter": "php vendor/phpunit/phpunit/phpunit --testsuite=Unit --filter testValidate --no-coverage --colors=always",
"check-phpunit-unit-no-coverage": [
    "Composer\\Config::disableProcessTimeout",
    "php vendor/phpunit/phpunit/phpunit --testsuite=Unit --no-coverage --configuration=/var/www/back/phpunit.xml --colors=always"
        ],
        ],
```

When I run the command in the project console:
`composer check-phpunit-vendor-version`
it gives me the answer:
`PHPUnit 11.0.5 by Sebastian Bergmann and contributors.`

When I run the command in the project console:
`composer check-phpunit-filter`
it gives me the answer:
......                                                              6 / 6 (100%)

Time: 01:20.563, Memory: 93.00 MB

When I run the command in the project console:
`composer check-phpunit-unit-no-coverage`
it gives me the answer:
```
PHPUnit 11.0.5 by Sebastian Bergmann and contributors.                                                      
Runtime:       PHP 8.2.7                              
Configuration: /var/www/back/phpunit.xml            
Fatal error: Non-readonly class PHPUnit\Framework\TestStatus\Success cannot extend reado
nly class PHPUnit\Framework\TestStatus\Known in /var/www/back/vendor/phpunit/phpunit/src
/Framework/TestStatus/Success.php on line 17
```

I am tracing debug this run the command:
`composer check-phpunit-unit-no-coverage`
in PHPUnit Framework in class TestStatus:
```
public static function success(): self
{
return new Success;
}
```
**when this is executed (new Success;), an error is generated (Non-readonly class ...)**
Class Hierarchy:
```
final readonly class Success extends Known
abstract readonly class Known extends TestStatus
abstract readonly class TestStatus
```

**Comment by scorpion3dd** [comment]
Deleted `symfony/phpunit-bridge`

When I run the command in the project console:
`composer check-phpunit-filter`
it gives me the answer:
```
...... 6 / 6 (100%)
Time: 01:20.563, Memory: 93.00 MB
```

When I run the command in the project console:
`composer check-phpunit-unit-no-coverage`
it gives me the answer:
```
PHPUnit 11.0.5 by Sebastian Bergmann and contributors.                                                      
Runtime:       PHP 8.2.7                              
Configuration: /var/www/back/phpunit.xml              

Fatal error: Non-readonly class PHPUnit\Framework\TestStatus\Success cannot extend reado
nly class PHPUnit\Framework\TestStatus\Known in /var/www/back/vendor/phpunit/phpunit/src
/Framework/TestStatus/Success.php on line 17

Fatal error: Uncaught PHPUnit\Event\Code\NoTestCaseObjectOnCallStackException: Cannot fi
nd TestCase object on call stack in /var/www/back/vendor/phpunit/phpunit/src/Event/Value
/Test/TestMethodBuilder.php:58
Stack trace:
#0 /var/www/back/vendor/phpunit/phpunit/src/Runner/ErrorHandler.php(64): PHPUnit\Event\C
ode\TestMethodBuilder::fromCallStack()
#1 [internal function]: PHPUnit\Runner\ErrorHandler->__invoke(2, 'Function must b...', '
/var/www/back/v...', 34)
#2 /var/www/back/vendor/symfony/error-handler/Error/FatalError.php(34): xdebug_get_funct
ion_stack()
#3 /var/www/back/vendor/symfony/error-handler/ErrorHandler.php(618): Symfony\Component\E
rrorHandler\Error\FatalError->__construct('Compile Error: ...', 0, Array, 2, true, NULL)
#4 [internal function]: Symfony\Component\ErrorHandler\ErrorHandler::handleFatalError() 
#5 {main}
  thrown in /var/www/back/vendor/phpunit/phpunit/src/Event/Value/Test/TestMethodBuilder.
php on line 58
```

**Comment by sebastianbergmann** [comment]
I am sorry, but I cannot debug your environment.

**Comment by antoinenedelecdecathlon** [comment]
FYI: If anyone end up reading this thread, you might be using [BypassFinals](https://github.com/dg/bypass-finals).

If that's the case, either remove that library, or else here is a [working solution](https://github.com/dg/bypass-finals/issues/53) for that.
